// Auto-generated by Glove Admin on 2026-02-25T15:43:04.550Z

window.GLOVES = 
[
  {
    "code": "2-LCTC",
    "name": "Pred Amber",
    "brand": "Coloursafe",
    "sizes": "7 - 11",
    "image": "Images/2-LCTC.jpg",
    "datasheet": "Datasheets/2-LCTC.pdf",
    "gauge": "2 Stand Seamless",
    "coating": "Crinkle Latex",
    "liner": "Polycotton Liner",
    "cutLevel": "Cut 1",
    "industries": [
      "Agriculture",
      "Construction",
      "Engineering",
      "Landscaping",
      "Scaffolding"
    ]
  },
  {
    "code": "BLACK-PUPL",
    "name": "Pred Jet",
    "brand": "Coloursafe",
    "sizes": "6 - 11",
    "image": "Images/BLACK-PUPL.jpg",
    "datasheet": "Datasheets/BLACK-PUPL.pdf",
    "gauge": "13",
    "coating": "PU",
    "liner": "Polyester Liner",
    "cutLevel": "Cut 1",
    "requirementsList": [
      "Vend Ready"
    ],
    "industries": [
      "Agriculture",
      "Banksmen",
      "Construction",
      "General Handling",
      "Scaffolding",
      "Warehousing"
    ]
  },
  {
    "code": "BLACK-PUPL-VR",
    "name": "Pred Jet - Vend",
    "brand": "Coloursafe",
    "sizes": "6 - 11",
    "image": "Images/BLACK-PUPL-VR.jpg",
    "datasheet": "Datasheets/BLACK-PUPL-VR.pdf",
    "gauge": "13",
    "coating": "PU",
    "liner": "Polyester Liner",
    "cutLevel": "Cut 1",
    "requirementsList": [
      "Vend Ready"
    ],
    "industries": [
      "Agriculture",
      "Banksmen",
      "Construction",
      "General Handling",
      "Scaffolding",
      "Warehousing"
    ]
  },
  {
    "code": "CCMPP",
    "name": "Pred Cotton Chrome",
    "brand": "Miscellaneous",
    "sizes": "10",
    "image": "Images/CCMPP.jpg",
    "datasheet": "Datasheets/CCMPP.pdf",
    "gauge": "8oz Cotton Drill",
    "coating": "Leather",
    "liner": "100% Cotton",
    "cutLevel": "Cut 1",
    "industries": [
      "Assembly",
      "Construction",
      "Gardening",
      "General Handling",
      "Packaging",
      "Warehousing"
    ]
  },
  {
    "code": "EZ-324-VR",
    "name": "Pred Ez-Grip",
    "brand": "Touchsafe",
    "sizes": "6 - 11",
    "image": "Images/EZ-324-VR.jpg",
    "datasheet": "Datasheets/EZ-324-VR.pdf",
    "gauge": "18",
    "coating": "Polymer",
    "liner": "Nylon Liner",
    "cutLevel": "Cut 1",
    "requirementsList": [
      "Foodsafe",
      "Touchscreen",
      "Vend Ready"
    ],
    "industries": [
      "Food Industry"
    ]
  },
  {
    "code": "HAR2",
    "name": "Pred Force",
    "brand": "Predator",
    "sizes": "10",
    "image": "Images/HAR2.jpg",
    "datasheet": "Datasheets/HAR2.pdf",
    "coating": "Leather",
    "leather": "Split Leather",
    "liner": "100% Cotton",
    "cutLevel": "Cut 2",
    "industries": [
      "Agriculture",
      "Construction",
      "Foresty",
      "General Handling",
      "Metal work",
      "Scaffolding",
      "Warehousing"
    ]
  },
  {
    "code": "HAWG2",
    "name": "Pred Thunder Red Mig",
    "brand": "Predator",
    "sizes": "11",
    "image": "Images/HAWG2.jpg",
    "datasheet": "Datasheets/HAWG2.pdf",
    "coating": "Leather",
    "leather": "Split Leather",
    "liner": "100% Cotton",
    "cutLevel": "Cut 2",
    "requirementsList": [
      "Contact Heat"
    ],
    "industries": [
      "Arc Welding",
      "Construction",
      "Engineering",
      "Fabrication",
      "Metal work",
      "Mig Welding",
      "Welding"
    ]
  },
  {
    "code": "KDZGGO-5",
    "name": "Pred Pup",
    "brand": "Miscellaneous",
    "sizes": "5",
    "image": "Images/KDZGGO-5.png",
    "datasheet": "Datasheets/KDZGGO-5.pdf",
    "gauge": "13",
    "coating": "TPE Palm Coating",
    "liner": "Polyester Liner",
    "requirementsList": [
      "Minimal Risk"
    ],
    "industries": [
      "Gardening",
      "General Handling"
    ]
  },
  {
    "code": "KDZGGY-4",
    "name": "Pred Cub",
    "brand": "Miscellaneous",
    "sizes": "4",
    "image": "Images/KDZGGY-4.png",
    "datasheet": "Datasheets/KDZGGY-4.pdf",
    "coating": "TPE Palm Coating",
    "liner": "Polyester Liner",
    "requirementsList": [
      "Minimal Risk"
    ],
    "industries": [
      "Gardening",
      "General Handling"
    ]
  },
  {
    "code": "LCPL-RED",
    "name": "Pred Fire",
    "brand": "Coloursafe",
    "sizes": "6 - 11",
    "image": "Images/LCPL-RED.jpg",
    "datasheet": "Datasheets/LCPL-RED.pdf",
    "gauge": "13",
    "coating": "Crinkle Latex",
    "liner": "Polyester Liner",
    "cutLevel": "Cut 1",
    "industries": [
      "Construction",
      "Engineering",
      "General Handling"
    ]
  },
  {
    "code": "LCTC-TD",
    "name": "Pred Paws",
    "brand": "Coloursafe",
    "sizes": "7 - 11",
    "image": "Images/LCTC-TD.jpg",
    "datasheet": "Datasheets/LCTC-TD.pdf",
    "coating": "Crinkle Latex",
    "liner": "Polycotton Liner",
    "cutLevel": "Cut 1",
    "industries": [
      "Agriculture",
      "Banksmen",
      "Construction",
      "Engineering",
      "Scaffolding"
    ]
  },
  {
    "code": "MF15A",
    "name": "Pred Graphite",
    "brand": "Touchsafe",
    "sizes": "6 - 11",
    "image": "Images/MF15A.jpg",
    "datasheet": "Datasheets/MF15A.pdf",
    "gauge": "15",
    "coating": "Nitrile Micro Foam",
    "liner": "Nylon Liner",
    "cutLevel": "Cut level A",
    "requirementsList": [
      "Contact Heat",
      "Touchscreen"
    ],
    "industries": [
      "Construction",
      "Food Industry",
      "General Handling",
      "Landscaping",
      "Packaging",
      "Scaffolding",
      "Touchscreens",
      "Warehousing"
    ]
  },
  {
    "code": "NFPL-R",
    "name": "Pred Cardinal",
    "brand": "Coloursafe",
    "sizes": "8 - 11",
    "image": "Images/NFPL-R.jpg",
    "datasheet": "Datasheets/NFPL-R.pdf",
    "gauge": "13",
    "coating": "Nitrile Foam",
    "liner": "Polyester Liner",
    "cutLevel": "Cut 1",
    "requirementsList": [
      "Contact Heat"
    ],
    "industries": [
      "Agriculture",
      "Banksmen",
      "Construction",
      "General Handling",
      "Landscaping"
    ]
  },
  {
    "code": "NITGFL330",
    "name": "Pred Boron",
    "brand": "Nitrile",
    "sizes": "S - 2XL",
    "image": "Images/NITGFL330.jpg",
    "datasheet": "Datasheets/NITGFL330.pdf",
    "coating": "Nitrile",
    "liner": "Flock Lined",
    "cutLevel": "Cut 1",
    "requirementsList": [
      "Foodsafe",
      "Touchscreen"
    ],
    "industries": [
      "Chemical",
      "Food Industry",
      "Janitorial",
      "Touchscreens"
    ]
  },
  {
    "code": "NITKW",
    "name": "Krypton (Knit-Wrist)",
    "brand": "Miscellaneous",
    "sizes": "8 - 11",
    "image": "Images/NITKW.jpg",
    "datasheet": "Datasheets/NITKW.pdf",
    "coating": "Nitrile",
    "liner": "Jersey Liner",
    "cutLevel": "Cut 1",
    "requirementsList": [
      "Waterproof"
    ],
    "industries": [
      "Banksmen",
      "Construction",
      "General Handling",
      "Packaging",
      "Scaffolding",
      "Warehousing"
    ]
  },
  {
    "code": "NITSC",
    "name": "Pred Radon (Safety Cuff)",
    "brand": "Miscellaneous",
    "sizes": "10",
    "image": "Images/NITSC.jpg",
    "datasheet": "Datasheets/NITSC.pdf",
    "coating": "Nitrile",
    "liner": "Jersey Liner",
    "cutLevel": "Cut 1",
    "industries": [
      "Banksmen",
      "Construction",
      "General Handling",
      "Packaging",
      "Scaffolding",
      "Warehousing"
    ]
  },
  {
    "code": "NSPL",
    "name": "Pred Scarlet",
    "brand": "Coloursafe",
    "sizes": "7 - 11",
    "image": "Images/NSPL.jpg",
    "datasheet": "Datasheets/NSPL.pdf",
    "gauge": "13",
    "coating": "Smooth Nitrile",
    "liner": "Polyester Liner",
    "cutLevel": "Cut 1",
    "industries": [
      "Agriculture",
      "Banksmen",
      "Construction",
      "Engineering",
      "General Handling",
      "Landscaping",
      "Scaffolding",
      "Warehousing"
    ]
  },
  {
    "code": "PRED 13-VR",
    "name": "Pred Sapphire - Vend",
    "brand": "Touchsafe",
    "sizes": "6 - 11",
    "image": "Images/PRED 13-VR.jpg",
    "datasheet": "Datasheets/PRED 13-VR.pdf",
    "gauge": "13",
    "coating": "Sandy Nitrile",
    "liner": "Polyethylene",
    "cutLevel": "Cut D",
    "requirementsList": [
      "Contact Heat",
      "Cut protection",
      "Touchscreen",
      "Vend Ready"
    ],
    "industries": [
      "Agriculture",
      "Construction",
      "Engineering",
      "Glass",
      "Glazing",
      "Metal work"
    ]
  },
  {
    "code": "PRED1",
    "name": "Pred Tiger",
    "brand": "Predator",
    "sizes": "10",
    "image": "Images/PRED1.jpg",
    "datasheet": "Datasheets/PRED1.pdf",
    "coating": "Leather",
    "leather": "Split Leather",
    "liner": "100% Cotton",
    "cutLevel": "Cut 2",
    "industries": [
      "Agriculture",
      "Construction",
      "Foresty",
      "General Handling",
      "Metal work",
      "Scaffolding",
      "Warehousing"
    ]
  },
  {
    "code": "PRED1-HV",
    "name": "Pred Hi-Vis Tiger",
    "brand": "Predator",
    "sizes": "10",
    "image": "Images/PRED1-HV.jpg",
    "datasheet": "Datasheets/PRED1-HV.pdf",
    "coating": "Leather",
    "leather": "Split Leather",
    "liner": "100% Cotton",
    "cutLevel": "Cut 2",
    "industries": [
      "Agriculture",
      "Construction",
      "Foresty",
      "Rigging",
      "Scaffolding"
    ]
  },
  {
    "code": "PRED12",
    "name": "Pred Needle",
    "brand": "Specialist",
    "sizes": "8 - 11",
    "image": "Images/PRED12.jpg",
    "datasheet": "Datasheets/PRED12.pdf",
    "gauge": "10",
    "coating": "Foam Latex",
    "liner": "Polyester Liner",
    "cutLevel": "Cut F",
    "requirementsList": [
      "Cut protection",
      "Needle Resistant",
      "Waterproof"
    ],
    "industries": [
      "Glass",
      "Glazing",
      "Metal work",
      "Needle Stick",
      "Recycling"
    ]
  },
  {
    "code": "PRED13",
    "name": "Pred Sapphire",
    "brand": "Coloursafe",
    "sizes": "7 - 11",
    "image": "Images/PRED13.jpg",
    "datasheet": "Datasheets/PRED13.pdf",
    "gauge": "13",
    "coating": "PU",
    "liner": "Polyester Liner",
    "cutLevel": "Cut F",
    "requirementsList": [
      "Cut protection",
      "Vend Ready"
    ],
    "industries": [
      "Agriculture",
      "Assembly",
      "Automotive",
      "Construction",
      "Engineering",
      "Fabrication",
      "Glass",
      "Sheet work"
    ]
  },
  {
    "code": "PRED16",
    "name": "Pred Anti-Vibe",
    "brand": "Specialist",
    "sizes": "7 - 11",
    "image": "Images/PRED16.jpg",
    "datasheet": "Datasheets/PRED16.pdf",
    "coating": "Leather",
    "leather": "Goat Skin",
    "cutLevel": "Cut 1",
    "requirementsList": [
      "Anti Vibration",
      "Vibration"
    ],
    "industries": [
      "Concrete Breakers",
      "Construction",
      "Engineering",
      "Mining"
    ]
  },
  {
    "code": "PRED2",
    "name": "Pred Hide Rigger Ivory",
    "brand": "Predator",
    "sizes": "10",
    "image": "Images/PRED2.jpg",
    "datasheet": "Datasheets/PRED2.pdf",
    "coating": "Leather",
    "leather": "Hide Leather",
    "liner": "100% Cotton",
    "cutLevel": "Cut 1",
    "industries": [
      "Agriculture",
      "Construction",
      "Foresty",
      "General Handling",
      "Metal work",
      "Scaffolding",
      "Warehousing"
    ]
  },
  {
    "code": "PRED2-GOLD",
    "name": "Pred Hide Rigger Gold",
    "brand": "Predator",
    "sizes": "10",
    "image": "Images/PRED2-GOLD.jpg",
    "datasheet": "Datasheets/PRED2-GOLD.pdf",
    "coating": "Leather",
    "leather": "Hide Leather",
    "liner": "100% Cotton",
    "cutLevel": "Cut 1",
    "industries": [
      "Agriculture",
      "Construction",
      "Foresty",
      "General Handling",
      "Metal work",
      "Scaffolding",
      "Warehousing"
    ]
  },
  {
    "code": "PRED3-15",
    "name": "Pred Ivory Drivers Glove",
    "brand": "Predator",
    "sizes": "10",
    "image": "Images/PRED3-15.jpg",
    "datasheet": "Datasheets/PRED3-15.pdf",
    "coating": "Leather",
    "leather": "Hide Leather",
    "liner": "100% Cotton",
    "cutLevel": "Cut 1",
    "industries": [
      "Agriculture",
      "Construction",
      "Foresty",
      "General Handling",
      "Logistics",
      "Scaffolding",
      "Warehousing"
    ]
  },
  {
    "code": "PRED3-GOLD",
    "name": "Pred Gold Drivers Glove",
    "brand": "Predator",
    "sizes": "10",
    "image": "Images/PRED3-GOLD.jpg",
    "datasheet": "Datasheets/PRED3-GOLD.pdf",
    "coating": "Leather",
    "leather": "Hide Leather",
    "liner": "100% Cotton",
    "cutLevel": "Cut 1",
    "industries": [
      "Agriculture",
      "Construction",
      "Foresty",
      "General Handling",
      "Logistics",
      "Rigging",
      "Scaffolding",
      "Warehousing"
    ]
  },
  {
    "code": "PRED3-SB",
    "name": "Pred Standard Driver",
    "brand": "Predator",
    "sizes": "10",
    "image": "Images/PRED3-SB.jpg",
    "datasheet": "Datasheets/PRED3-SB.pdf",
    "coating": "Leather",
    "leather": "Hide Leather",
    "liner": "100% Cotton",
    "cutLevel": "Cut 1",
    "industries": [
      "Agriculture",
      "Construction",
      "General Handling",
      "Rigging",
      "Scaffolding",
      "Warehousing"
    ]
  },
  {
    "code": "PRED4",
    "name": "Pred Signature Mig Gauntlet",
    "brand": "Predator",
    "sizes": "11",
    "image": "Images/PRED4.jpg",
    "datasheet": "Datasheets/PRED4.pdf",
    "coating": "Leather",
    "leather": "Split Leather",
    "liner": "100% Cotton",
    "cutLevel": "Cut 2",
    "requirementsList": [
      "Contact Heat"
    ],
    "industries": [
      "Arc Welding",
      "Construction",
      "Engineering",
      "Fabrication",
      "Metal work",
      "Mig Welding",
      "Welding"
    ]
  },
  {
    "code": "PRED4-16",
    "name": "Pred Signature 16\" Mig Gauntlet",
    "brand": "Predator",
    "sizes": "11",
    "image": "Images/PRED4-16.jpg",
    "datasheet": "Datasheets/PRED4-16.pdf",
    "coating": "Leather",
    "leather": "Split Leather",
    "liner": "100% Cotton",
    "cutLevel": "Cut 2",
    "requirementsList": [
      "Contact Heat"
    ],
    "industries": [
      "Arc Welding",
      "Construction",
      "Fabrication",
      "Forging",
      "Metal work",
      "Mig Welding",
      "Welding"
    ]
  },
  {
    "code": "PRED4-GLOVE",
    "name": "Pred 4 Glove",
    "brand": "Predator",
    "sizes": "10",
    "image": "Images/PRED4-GLOVE.jpg",
    "datasheet": "Datasheets/PRED4-GLOVE.pdf",
    "coating": "Leather",
    "leather": "Split Leather",
    "liner": "100% Cotton",
    "cutLevel": "Cut 1",
    "requirementsList": [
      "Contact Heat"
    ],
    "industries": [
      "Construction",
      "Engineering",
      "Fabrication",
      "Forging",
      "Metal work"
    ]
  },
  {
    "code": "PRED4-THORN",
    "name": "Pred Thornproof",
    "brand": "Specialist",
    "sizes": "11",
    "image": "Images/PRED4-THORN.jpg",
    "datasheet": "Datasheets/PRED4-THORN.pdf",
    "coating": "Leather",
    "leather": "Split Leather",
    "liner": "100% Cotton",
    "cutLevel": "Cut 2",
    "requirementsList": [
      "Contact Heat",
      "Needle Resistant"
    ],
    "industries": [
      "Foresty",
      "Gardening",
      "Landscaping"
    ]
  },
  {
    "code": "PRED6",
    "name": "Pred Signature Tig",
    "brand": "Predator",
    "sizes": "10",
    "image": "Images/PRED6.jpg",
    "datasheet": "Datasheets/PRED6.pdf",
    "coating": "Leather",
    "leather": "Hide Leather",
    "liner": "100% Cotton",
    "cutLevel": "Cut 1",
    "requirementsList": [
      "Contact Heat"
    ],
    "industries": [
      "Agriculture",
      "Construction",
      "Engineering",
      "Forging",
      "Metal work",
      "Tig Welding",
      "Welding"
    ]
  },
  {
    "code": "PRED6-C",
    "name": "Pred Standard Tig",
    "brand": "Predator",
    "sizes": "10",
    "image": "Images/PRED6-C.jpg",
    "datasheet": "Datasheets/PRED6-C.pdf",
    "coating": "Leather",
    "leather": "Hide Leather",
    "liner": "100% Cotton",
    "cutLevel": "Cut 1",
    "requirementsList": [
      "Contact Heat"
    ],
    "industries": [
      "Agriculture",
      "Construction",
      "Engineering",
      "Forging",
      "Metal work",
      "Tig Welding",
      "Welding"
    ]
  },
  {
    "code": "PRED6-D",
    "name": "Pred Deerskin Tig",
    "brand": "Predator",
    "sizes": "10",
    "image": "Images/PRED6-D.jpg",
    "datasheet": "Datasheets/PRED6-D.pdf",
    "coating": "Leather",
    "leather": "Deer Hide",
    "liner": "100% Cotton",
    "cutLevel": "Cut 1",
    "requirementsList": [
      "Contact Heat"
    ],
    "industries": [
      "Agriculture",
      "Construction",
      "Engineering",
      "Forging",
      "Metal work",
      "Tig Welding",
      "Welding"
    ]
  },
  {
    "code": "PRED6-GLOVE",
    "name": "Pred 6 Glove",
    "brand": "Predator",
    "sizes": "10",
    "image": "Images/PRED6-GLOVE.jpg",
    "datasheet": "Datasheets/PRED6-GLOVE.pdf",
    "coating": "Leather",
    "leather": "Hide Leather",
    "liner": "100% Cotton",
    "cutLevel": "Cut 1",
    "requirementsList": [
      "Contact Heat"
    ],
    "industries": [
      "Agriculture",
      "Construction",
      "Engineering",
      "Forging",
      "Metal work"
    ]
  },
  {
    "code": "PRKW-10",
    "name": "Pred PVC Knit Wrist",
    "brand": "Miscellaneous",
    "sizes": "10",
    "image": "Images/PRKW-10.jpg",
    "datasheet": "Datasheets/PRKW-10.pdf",
    "coating": "PVC",
    "liner": "Jersey Liner",
    "cutLevel": "Cut 1",
    "industries": [
      "Assembly",
      "Construction",
      "Gardening",
      "General Handling",
      "Packaging",
      "Warehousing"
    ]
  },
  {
    "code": "PU13D",
    "name": "Pred Delta",
    "brand": "Coloursafe",
    "sizes": "6 - 11",
    "image": "Images/PU13D.jpg",
    "datasheet": "Datasheets/PU13D.pdf",
    "gauge": "13",
    "coating": "PU",
    "liner": "Polyester Liner",
    "cutLevel": "Cut D",
    "requirementsList": [
      "Cut protection"
    ],
    "industries": [
      "Agriculture",
      "Construction",
      "Engineering",
      "General Handling",
      "Glass",
      "Landscaping",
      "Packaging",
      "Scaffolding",
      "Warehousing"
    ]
  },
  {
    "code": "PUPL",
    "name": "Pred Ruby",
    "brand": "Coloursafe",
    "sizes": "7 - 11",
    "image": "Images/PUPL.jpg",
    "datasheet": "Datasheets/PUPL.pdf",
    "gauge": "13",
    "coating": "PU",
    "liner": "Polyester Liner",
    "cutLevel": "Cut 1",
    "industries": [
      "Automotive",
      "Banksmen",
      "Construction",
      "Engineering",
      "General Handling",
      "Landscaping",
      "Scaffolding",
      "Warehousing"
    ]
  },
  {
    "code": "PUUH-13",
    "name": "Pred Emerald",
    "brand": "Coloursafe",
    "sizes": "7 - 11",
    "image": "Images/PUUH-13.jpg",
    "datasheet": "Datasheets/PUUH-13.pdf",
    "gauge": "13",
    "coating": "PU",
    "liner": "Azura Liner",
    "cutLevel": "Cut C",
    "requirementsList": [
      "Cut protection"
    ],
    "industries": [
      "Construction",
      "Engineering",
      "General Handling",
      "Landscaping",
      "Scaffolding"
    ]
  },
  {
    "code": "RD300199Q",
    "name": "Nitrylex Classic Blue",
    "brand": "Nitrile",
    "sizes": "S - 2XL",
    "image": "Images/RD300199Q.jpg",
    "datasheet": "Datasheets/RD300199Q.pdf",
    "coating": "Nitrile",
    "style": [
      "Disposable",
      "Latex free",
      "Powder free",
      "Silicone free"
    ],
    "requirementsList": [
      "Foodsafe",
      "Touchscreen",
      "Waterproof"
    ],
    "industries": [
      "Food Industry",
      "Janitorial",
      "Plumbing",
      "Touchscreens",
      "Veterinary"
    ]
  },
  {
    "code": "RD3009600",
    "name": "Nitrylex Classic Blue (200's)",
    "brand": "Nitrile",
    "sizes": "S - 2XL",
    "image": "Images/RD3009600.jpg",
    "datasheet": "Datasheets/RD3009600.pdf",
    "coating": "Nitrile",
    "style": [
      "Disposable",
      "Latex free",
      "Powder free",
      "Silicone free"
    ],
    "requirementsList": [
      "Foodsafe",
      "Touchscreen",
      "Waterproof"
    ],
    "industries": [
      "Agriculture",
      "Asbestos",
      "Assembly",
      "Automotive",
      "Chemical",
      "Construction",
      "Food Industry",
      "Insulation",
      "Janitorial",
      "Plumbing",
      "Touchscreens",
      "Veterinary"
    ]
  },
  {
    "code": "RD301040Q",
    "name": "Nitrylex Classic Black",
    "brand": "Nitrile",
    "sizes": "S - 2XL",
    "image": "Images/RD301040Q.jpg",
    "datasheet": "Datasheets/RD301040Q.pdf",
    "coating": "Nitrile",
    "style": [
      "Disposable",
      "Latex free",
      "Powder free",
      "Silicone free"
    ],
    "requirementsList": [
      "Foodsafe",
      "Touchscreen",
      "Waterproof"
    ],
    "industries": [
      "Asbestos",
      "Assembly",
      "Automotive",
      "Chemical",
      "Engineering",
      "Food Industry",
      "General Handling",
      "Insulation",
      "Janitorial",
      "Plumbing",
      "Touchscreens",
      "Veterinary"
    ]
  },
  {
    "code": "RD302370Q",
    "name": "Nitrylex Strong",
    "brand": "Nitrile",
    "sizes": "S - 2XL",
    "image": "Images/RD302370Q.jpg",
    "datasheet": "Datasheets/RD302370Q.pdf",
    "coating": "Nitrile",
    "style": [
      "Disposable",
      "Latex free",
      "Powder free",
      "Silicone free"
    ],
    "requirementsList": [
      "Foodsafe",
      "Touchscreen",
      "Waterproof"
    ],
    "industries": [
      "Agriculture",
      "Asbestos",
      "Assembly",
      "Automotive",
      "Chemical",
      "Engineering",
      "Food Industry",
      "Insulation",
      "Janitorial",
      "Plumbing",
      "Touchscreens",
      "Veterinary"
    ]
  },
  {
    "code": "RD3029200",
    "name": "Nitrylex Basic",
    "brand": "Nitrile",
    "sizes": "S - XL",
    "image": "Images/RD3029200.jpg",
    "datasheet": "Datasheets/RD3029200.pdf",
    "coating": "Nitrile",
    "style": [
      "Disposable",
      "Latex free",
      "Powder free",
      "Silicone free"
    ],
    "requirementsList": [
      "Foodsafe",
      "Touchscreen",
      "Waterproof"
    ],
    "industries": [
      "Agriculture",
      "Assembly",
      "Automotive",
      "Construction",
      "Insulation",
      "Janitorial",
      "Plumbing",
      "Veterinary"
    ]
  },
  {
    "code": "RP300146Q",
    "name": "Ideall Grip Orange (100's)",
    "brand": "Nitrile",
    "sizes": "S - 2XL",
    "image": "Images/RP300146Q.jpg",
    "datasheet": "Datasheets/RP300146Q.pdf",
    "coating": "Nitrile",
    "style": [
      "Diamond grip",
      "Disposable",
      "Latex free",
      "Powder free",
      "Silicone free"
    ],
    "requirementsList": [
      "Foodsafe",
      "Touchscreen",
      "Waterproof"
    ],
    "industries": [
      "Agriculture",
      "Assembly",
      "Automotive",
      "Construction",
      "Engineering",
      "Insulation",
      "Janitorial",
      "Plumbing",
      "Veterinary"
    ]
  },
  {
    "code": "RP300260Q",
    "name": "Ideall Grip Black",
    "brand": "Nitrile",
    "sizes": "S - 2XL",
    "image": "Images/RP300260Q.jpg",
    "datasheet": "Datasheets/RP300260Q.pdf",
    "coating": "Nitrile",
    "style": [
      "Diamond grip",
      "Disposable",
      "Latex free",
      "Powder free",
      "Silicone free"
    ],
    "requirementsList": [
      "Foodsafe",
      "Touchscreen",
      "Waterproof"
    ],
    "industries": [
      "Asbestos",
      "Assembly",
      "Automotive",
      "Chemical",
      "Engineering",
      "Food Industry",
      "Insulation",
      "Janitorial",
      "Plumbing",
      "Touchscreens",
      "Veterinary"
    ]
  },
  {
    "code": "RP300270Q",
    "name": "Ideall Grip Orange",
    "brand": "Nitrile",
    "sizes": "S - 2XL",
    "image": "Images/RP300270Q.jpg",
    "datasheet": "Datasheets/RP300270Q.pdf",
    "coating": "Nitrile",
    "style": [
      "Diamond grip",
      "Disposable",
      "Latex free",
      "Powder free",
      "Silicone free"
    ],
    "requirementsList": [
      "Foodsafe",
      "Touchscreen",
      "Waterproof"
    ],
    "industries": [
      "Asbestos",
      "Assembly",
      "Chemical",
      "Food Industry",
      "Insulation",
      "Janitorial",
      "Plumbing",
      "Touchscreens",
      "Veterinary"
    ]
  },
  {
    "code": "RP300326Q",
    "name": "Ideall Grip Green",
    "brand": "Nitrile",
    "sizes": "S - 2XL",
    "image": "Images/RP300326Q.jpg",
    "datasheet": "Datasheets/RP300326Q.pdf",
    "coating": "Nitrile",
    "style": [
      "Diamond grip",
      "Disposable",
      "Latex free",
      "Powder free",
      "Silicone free"
    ],
    "requirementsList": [
      "Foodsafe",
      "Touchscreen",
      "Waterproof"
    ],
    "industries": [
      "Agriculture",
      "Asbestos",
      "Assembly",
      "Automotive",
      "Chemical",
      "Construction",
      "Engineering",
      "Food Industry",
      "Insulation",
      "Janitorial",
      "Plumbing",
      "Touchscreens",
      "Veterinary"
    ]
  },
  {
    "code": "RP300376Q",
    "name": "Ideall Grip Blue (Long Cuff)",
    "brand": "Nitrile",
    "sizes": "S - 2XL",
    "image": "Images/RP300376Q.jpg",
    "datasheet": "Datasheets/RP300376Q.pdf",
    "coating": "Nitrile",
    "style": [
      "Diamond grip",
      "Disposable",
      "Latex free",
      "Powder free",
      "Silicone free"
    ],
    "requirementsList": [
      "Foodsafe",
      "Touchscreen",
      "Waterproof"
    ],
    "industries": [
      "Asbestos",
      "Assembly",
      "Automotive",
      "Chemical",
      "Engineering",
      "Food Industry",
      "General Handling",
      "Insulation",
      "Janitorial",
      "Plumbing",
      "Touchscreens",
      "Veterinary"
    ]
  },
  {
    "code": "RPET10DW",
    "name": "Pred Spruce",
    "brand": "Planetsafe",
    "sizes": "7 - 11",
    "image": "Images/RPET10DW.jpg",
    "datasheet": "Datasheets/RPET10DW.pdf",
    "gauge": "10",
    "coating": "Foam Latex",
    "liner": "Metal Q",
    "cutLevel": "Cut D",
    "requirementsList": [
      "Contact Heat",
      "Contact cold",
      "Cut protection",
      "Thermal"
    ],
    "industries": [
      "Automotive",
      "Cold stores",
      "Engineering",
      "Rigging",
      "Scaffolding",
      "Warehousing"
    ]
  },
  {
    "code": "RPET15A",
    "name": "Pred Cedar",
    "brand": "Planetsafe",
    "sizes": "6 - 11",
    "image": "Images/RPET15A.jpg",
    "datasheet": "Datasheets/RPET15A.pdf",
    "gauge": "15",
    "coating": "Nitrile Foam",
    "liner": "Polyester Liner",
    "cutLevel": "Cut 1",
    "requirementsList": [
      "Contact Heat"
    ],
    "industries": [
      "Construction",
      "General Handling",
      "Landscaping",
      "Logistics",
      "Packaging",
      "Warehousing"
    ]
  },
  {
    "code": "RPET15E",
    "name": "Pred Maple",
    "brand": "Planetsafe",
    "sizes": "6 - 11",
    "image": "Images/RPET15E.jpg",
    "datasheet": "Datasheets/RPET15E.pdf",
    "gauge": "15",
    "coating": "Sandy Nitrile",
    "liner": "Metal Q",
    "cutLevel": "Cut E",
    "requirementsList": [
      "Cut protection",
      "Touchscreen"
    ],
    "industries": [
      "Agriculture",
      "Assembly",
      "Construction",
      "Engineering",
      "Fabrication",
      "Glass",
      "Glazing"
    ]
  },
  {
    "code": "RS1B-VL",
    "name": "Pred Power Plus XL",
    "brand": "Predator",
    "sizes": "11.5",
    "image": "Images/RS1B-VL.jpg",
    "datasheet": "Datasheets/RS1B-VL.pdf",
    "coating": "Leather",
    "leather": "Split Leather",
    "liner": "100% Cotton",
    "cutLevel": "Cut 1",
    "industries": [
      "Agriculture",
      "Construction",
      "Foresty",
      "Rigging",
      "Scaffolding",
      "Warehousing"
    ]
  },
  {
    "code": "RS1C-TH",
    "name": "Pred Winter Power",
    "brand": "Predator",
    "sizes": "10",
    "image": "Images/RS1C-TH.jpg",
    "datasheet": "Datasheets/RS1C-TH.pdf",
    "coating": "Leather",
    "liner": "Thinsulate Liner",
    "cutLevel": "Cut 1",
    "requirementsList": [
      "Contact Heat",
      "Contact cold"
    ],
    "industries": [
      "Cold stores",
      "Construction",
      "Logistics",
      "Rigging",
      "Scaffolding",
      "Warehousing"
    ]
  },
  {
    "code": "RS2DP-B",
    "name": "Pred Power Plus Double Palm",
    "brand": "Predator",
    "sizes": "10",
    "image": "Images/RS2DP-B.jpg",
    "datasheet": "Datasheets/RS2DP-B.pdf",
    "coating": "Leather",
    "leather": "Split Leather",
    "liner": "100% Cotton",
    "cutLevel": "Cut 2",
    "requirementsList": [
      "Contact Heat"
    ],
    "industries": [
      "Agriculture",
      "Construction",
      "Foresty",
      "General Handling",
      "Metal work",
      "Scaffolding",
      "Warehousing"
    ]
  },
  {
    "code": "RSW1C",
    "name": "Pred Lightning Red Mig",
    "brand": "Predator",
    "sizes": "11",
    "image": "Images/RSW1C.jpg",
    "datasheet": "Datasheets/RSW1C.pdf",
    "coating": "Leather",
    "leather": "Split Leather",
    "liner": "100% Cotton",
    "cutLevel": "Cut 1",
    "requirementsList": [
      "Contact Heat"
    ],
    "industries": [
      "Arc Welding",
      "Construction",
      "Engineering",
      "Fabrication",
      "Metal work",
      "Mig Welding",
      "Welding"
    ]
  },
  {
    "code": "RSW1C-BLUE",
    "name": "Pred Lightning Blue Mig",
    "brand": "Predator",
    "sizes": "11",
    "image": "Images/RSW1C-BLUE.jpg",
    "datasheet": "Datasheets/RSW1C-BLUE.pdf",
    "coating": "Leather",
    "leather": "Split Leather",
    "liner": "100% Cotton",
    "cutLevel": "Cut 1",
    "requirementsList": [
      "Contact Heat"
    ],
    "industries": [
      "Arc Welding",
      "Construction",
      "Engineering",
      "Fabrication",
      "Forging",
      "Mig Welding",
      "Welding"
    ]
  },
  {
    "code": "RSW1C-BLUE-S",
    "name": "Pred Lightning Blue Small",
    "brand": "Predator",
    "sizes": "9",
    "image": "Images/RSW1C-BLUE-S.jpg",
    "datasheet": "Datasheets/RSW1C-BLUE-S.pdf",
    "coating": "Leather",
    "leather": "Split Leather",
    "liner": "100% Cotton",
    "cutLevel": "Cut 1",
    "requirementsList": [
      "Contact Heat"
    ],
    "industries": [
      "Arc Welding",
      "Construction",
      "Engineering",
      "Fabrication",
      "Forging",
      "Mig Welding"
    ]
  },
  {
    "code": "RSW1C-KEV",
    "name": "Pred Lightning Twaron Mig",
    "brand": "Predator",
    "sizes": "11",
    "image": "Images/RSW1C-KEV.jpg",
    "datasheet": "Datasheets/RSW1C-KEV.pdf",
    "coating": "Leather",
    "leather": "Split Leather",
    "liner": "100% Cotton",
    "cutLevel": "Cut 1",
    "requirementsList": [
      "Contact Heat"
    ],
    "industries": [
      "Arc Welding",
      "Construction",
      "Engineering",
      "Fabrication",
      "Metal work",
      "Mig Welding",
      "Welding"
    ]
  },
  {
    "code": "RSW1C-REV",
    "name": "Pred Lightning Reversible",
    "brand": "Predator",
    "sizes": "11",
    "image": "Images/RSW1C-REV.jpg",
    "datasheet": "Datasheets/RSW1C-REV.pdf",
    "coating": "Leather",
    "leather": "Split Leather",
    "liner": "100% Cotton",
    "cutLevel": "Cut 1",
    "requirementsList": [
      "Contact Heat"
    ],
    "industries": [
      "Arc Welding",
      "Construction",
      "Engineering",
      "Fabrication",
      "Metal work",
      "Mig Welding"
    ]
  },
  {
    "code": "SL1HRF",
    "name": "Pred Cobra Sleeve",
    "brand": "Miscellaneous",
    "sizes": "45CM",
    "image": "Images/SL1HRF.png",
    "datasheet": "Datasheets/SL1HRF.pdf",
    "gauge": "18",
    "liner": "Nylon Liner",
    "cutLevel": "Cut F",
    "style": [
      "Sleeves"
    ],
    "requirementsList": [
      "Contact Heat",
      "Cut protection"
    ],
    "industries": [
      "Agriculture",
      "Automotive",
      "Engineering",
      "Sheet work"
    ]
  },
  {
    "code": "SL2CLD",
    "name": "Pred Python Sleeve",
    "brand": "Miscellaneous",
    "sizes": "45CM",
    "image": "Images/SL2CLD.jpg",
    "datasheet": "Datasheets/SL2CLD.pdf",
    "gauge": "18",
    "liner": "Metal Q",
    "cutLevel": "Cut D",
    "style": [
      "Sleeves"
    ],
    "requirementsList": [
      "Cut protection"
    ],
    "industries": [
      "Agriculture",
      "Automotive",
      "Engineering",
      "Sheet work"
    ]
  },
  {
    "code": "SL3VIPD",
    "name": "Pred Viper Sleeve",
    "brand": "Miscellaneous",
    "sizes": "45CM",
    "image": "Images/SL3VIPD.jpg",
    "datasheet": "Datasheets/SL3VIPD.pdf",
    "gauge": "13",
    "liner": "Nylon Liner",
    "cutLevel": "Cut D",
    "style": [
      "Sleeves"
    ],
    "requirementsList": [
      "Cut protection"
    ],
    "industries": [
      "Agriculture",
      "Automotive",
      "Engineering",
      "Sheet work"
    ]
  },
  {
    "code": "SN13DTQ",
    "name": "Pred Sigma",
    "brand": "Touchsafe",
    "sizes": "6 - 11",
    "image": "Images/SN13DTQ.jpg",
    "datasheet": "Datasheets/SN13DTQ.pdf",
    "gauge": "13",
    "coating": "Sandy Nitrile",
    "liner": "Polyethylene",
    "cutLevel": "Cut D",
    "requirementsList": [
      "Contact Heat",
      "Cut protection",
      "Touchscreen",
      "Vend Ready"
    ],
    "industries": [
      "Agriculture",
      "Construction",
      "Food Industry",
      "Glass",
      "Glazing",
      "Landscaping",
      "Metal work",
      "Packaging",
      "Scaffolding",
      "Touchscreens",
      "Warehousing"
    ]
  },
  {
    "code": "SN13DTQ-VR",
    "name": "Pred Sigma - Vend",
    "brand": "Touchsafe",
    "sizes": "6 - 11",
    "image": "Images/SN13DTQ-VR.jpg",
    "datasheet": "Datasheets/SN13DTQ-VR.pdf",
    "gauge": "13",
    "coating": "Sandy Nitrile",
    "liner": "Polyethylene",
    "cutLevel": "Cut D",
    "requirementsList": [
      "Contact Heat",
      "Touchscreen",
      "Vend Ready"
    ],
    "industries": [
      "Agriculture",
      "Construction",
      "Engineering",
      "Glass",
      "Glazing",
      "Metal work"
    ]
  },
  {
    "code": "STLKW",
    "name": "Stockinette Knit Wrist - M",
    "brand": "Miscellaneous",
    "sizes": "Medium",
    "image": "Images/STLKW.jpg",
    "datasheet": "Datasheets/STLKW.pdf",
    "liner": "100% Cotton",
    "requirementsList": [
      "Minimal Risk"
    ],
    "industries": [
      "Assembly",
      "General Handling",
      "Inspection",
      "Packaging",
      "Warehousing"
    ]
  },
  {
    "code": "STMKW",
    "name": "Stockinette Knit Wrist - L",
    "brand": "Miscellaneous",
    "sizes": "Large",
    "image": "Images/STMKW.jpg",
    "datasheet": "Datasheets/STMKW.pdf",
    "liner": "100% Cotton",
    "requirementsList": [
      "Minimal Risk"
    ],
    "industries": [
      "Assembly",
      "General Handling",
      "Inspection",
      "Packaging",
      "Warehousing"
    ]
  },
  {
    "code": "TS1",
    "name": "Pred Sensor",
    "brand": "Touchsafe",
    "sizes": "6 - 11",
    "image": "Images/TS1.jpg",
    "datasheet": "Datasheets/TS1.pdf",
    "gauge": "15",
    "coating": "Polymax",
    "liner": "Nylon Liner",
    "cutLevel": "Cut 1",
    "requirementsList": [
      "Contact Heat",
      "Foodsafe",
      "Touchscreen"
    ],
    "industries": [
      "Assembly",
      "Automotive",
      "Engineering",
      "Food Industry",
      "Touchscreens"
    ]
  },
  {
    "code": "TS4",
    "name": "Pred Impact",
    "brand": "Touchsafe",
    "sizes": "8 - 11",
    "image": "Images/TS4.jpg",
    "datasheet": "Datasheets/TS4.pdf",
    "gauge": "18",
    "coating": "Polymax",
    "liner": "Nylon Liner",
    "cutLevel": "Cut F",
    "requirementsList": [
      "Contact Heat",
      "Cut protection",
      "Foodsafe",
      "Impact",
      "Touchscreen"
    ],
    "industries": [
      "Automotive",
      "Fabrication",
      "Food Industry",
      "Glass",
      "Glazing",
      "Metal work",
      "Touchscreens"
    ]
  },
  {
    "code": "WPTL7CL",
    "name": "Pred Alaska",
    "brand": "Coloursafe",
    "sizes": "7 - 11",
    "image": "Images/WPTL7CL.jpg",
    "datasheet": "Datasheets/WPTL7CL.pdf",
    "gauge": "7",
    "coating": "Crinkle Latex",
    "liner": "Polyester Liner",
    "cutLevel": "Cut 1",
    "requirementsList": [
      "Contact cold",
      "Thermal"
    ],
    "industries": [
      "Agriculture",
      "Banksmen",
      "Cold stores",
      "Construction",
      "Engineering",
      "Scaffolding"
    ]
  },
  {
    "code": "WS1",
    "name": "Pred Atlantic",
    "brand": "Watersafe",
    "sizes": "7 - 11",
    "image": "Images/WS1.jpg",
    "datasheet": "Datasheets/WS1.pdf",
    "gauge": "15",
    "coating": "Latex",
    "liner": "Nylon Liner",
    "cutLevel": "Cut 1",
    "requirementsList": [
      "Contact Heat",
      "Waterproof"
    ],
    "industries": [
      "Banksmen",
      "Construction",
      "Engineering",
      "General Handling",
      "Landscaping",
      "Scaffolding"
    ]
  },
  {
    "code": "WS4",
    "name": "Pred Baltic",
    "brand": "Watersafe",
    "sizes": "7 - 11",
    "image": "Images/WS4.jpg",
    "datasheet": "Datasheets/WS4.pdf",
    "gauge": "15",
    "coating": "Latex",
    "liner": "Acrylic liner",
    "cutLevel": "Cut 2",
    "requirementsList": [
      "Contact Heat",
      "Contact cold",
      "Waterproof"
    ],
    "industries": [
      "Cold stores",
      "Construction",
      "Engineering",
      "Landscaping",
      "Logistics",
      "Scaffolding"
    ]
  },
  {
    "code": "WS5",
    "name": "Pred Arctic",
    "brand": "Watersafe",
    "sizes": "8 - 11",
    "image": "Images/WS5.jpg",
    "datasheet": "Datasheets/WS5.pdf",
    "gauge": "13",
    "coating": "Sandy Nitrile",
    "liner": "Acrylic liner",
    "cutLevel": "Cut E",
    "requirementsList": [
      "Contact Heat",
      "Contact cold",
      "Thermal",
      "Waterproof"
    ],
    "industries": [
      "Cold stores",
      "Construction",
      "Engineering",
      "Metal work",
      "Recycling",
      "Waste Management"
    ]
  },
  {
    "code": "WS6",
    "name": "Pred Congo",
    "brand": "Watersafe",
    "sizes": "6 - 11",
    "image": "Images/WS6.jpg",
    "datasheet": "Datasheets/WS6.pdf",
    "gauge": "7",
    "coating": "Crinkle Latex",
    "liner": "Polyester Liner",
    "cutLevel": "Cut 1",
    "requirementsList": [
      "Waterproof"
    ],
    "industries": [
      "Banksmen",
      "Construction",
      "Engineering",
      "General Handling",
      "Landscaping",
      "Scaffolding"
    ]
  },
  {
    "code": "WS7",
    "name": "Pred Yukon",
    "brand": "Watersafe",
    "sizes": "7 - 11",
    "image": "Images/WS7.jpg",
    "datasheet": "Datasheets/WS7.pdf",
    "gauge": "15",
    "coating": "Latex",
    "liner": "Polyester Liner",
    "cutLevel": "Cut E",
    "requirementsList": [
      "Contact cold",
      "Cut protection",
      "Thermal",
      "Waterproof"
    ],
    "industries": [
      "Cold stores",
      "Construction",
      "Engineering",
      "General Handling",
      "Glass",
      "Recycling",
      "Waste Management"
    ]
  },
  {
    "code": "WS8",
    "name": "Pred Persian",
    "brand": "Watersafe",
    "sizes": "6 - 11",
    "image": "Images/WS8.jpg",
    "datasheet": "Datasheets/WS8.pdf",
    "gauge": "15",
    "coating": "Sandy Nitrile",
    "liner": "Nylon Liner",
    "cutLevel": "Cut 1",
    "requirementsList": [
      "Contact Heat",
      "Waterproof"
    ],
    "industries": [
      "Cold stores",
      "Construction",
      "Engineering",
      "General Handling",
      "Landscaping",
      "Scaffolding"
    ]
  },
  {
    "code": "WS9",
    "name": "Pred Caspian",
    "brand": "Watersafe",
    "sizes": "7 - 11",
    "image": "Images/WS9.jpg",
    "datasheet": "Datasheets/WS9.pdf",
    "gauge": "13",
    "coating": "Sandy Nitrile",
    "liner": "Nylon Liner",
    "cutLevel": "Cut F",
    "requirementsList": [
      "Contact Heat",
      "Cut protection",
      "Waterproof"
    ],
    "industries": [
      "Banksmen",
      "Engineering",
      "Glass",
      "Recycling"
    ]
  }
];

window.FILTERS = 
{
  "categories": {
    "Brand": [
      "Coloursafe",
      "Miscellaneous",
      "Nitrile",
      "Planetsafe",
      "Predator",
      "Specialist",
      "Touchsafe",
      "Watersafe"
    ],
    "Coating": [
      "Crinkle Latex",
      "Foam Latex",
      "Latex",
      "Leather",
      "Nitrile",
      "Nitrile Foam",
      "Nitrile Micro Foam",
      "PU",
      "PVC",
      "Polymax",
      "Polymer",
      "Sandy Nitrile",
      "Smooth Nitrile",
      "TPE Palm Coating"
    ],
    "Cut Level": [
      "Cut 1",
      "Cut 2",
      "Cut C",
      "Cut D",
      "Cut E",
      "Cut F",
      "Cut level A",
      "Cut level B"
    ],
    "Gauge": [
      "10",
      "13",
      "15",
      "18",
      "2 Stand Seamless",
      "7",
      "8oz Cotton Drill"
    ],
    "Industry": [
      "Agriculture",
      "Arc Welding",
      "Asbestos",
      "Assembly",
      "Automotive",
      "Banksmen",
      "Chemical",
      "Cold stores",
      "Concrete Breakers",
      "Construction",
      "Engineering",
      "Fabrication",
      "Food Industry",
      "Foresty",
      "Forging",
      "Gardening",
      "General Handling",
      "Glass",
      "Glazing",
      "Inspection",
      "Insulation",
      "Janitorial",
      "Landscaping",
      "Logistics",
      "Metal work",
      "Mig Welding",
      "Mining",
      "Needle Stick",
      "Packaging",
      "Plumbing",
      "Recycling",
      "Refuse",
      "Rigging",
      "Scaffolding",
      "Sheet work",
      "Tig Welding",
      "Touchscreens",
      "Veterinary",
      "Warehousing",
      "Waste Management",
      "Welding"
    ],
    "Leather": [
      "Deer Hide",
      "Goat Skin",
      "Hide Leather",
      "Split Leather"
    ],
    "Liner Material": [
      "100% Cotton",
      "Acrylic liner",
      "Azura Liner",
      "Flock Lined",
      "Jersey Liner",
      "Metal Q",
      "Natural Cotton Liner",
      "Nylon Liner",
      "Polycotton Liner",
      "Polyester Liner",
      "Polyethylene",
      "Recycled Polyester",
      "Spandex liner",
      "Steel liner",
      "Tekarmor",
      "Thinsulate Liner",
      "UHMWPE"
    ],
    "Requirements": [
      "Anti Vibration",
      "Contact Heat",
      "Contact cold",
      "Cut protection",
      "Foodsafe",
      "Impact",
      "Minimal Risk",
      "Needle Resistant",
      "Thermal",
      "Touchscreen",
      "Vend Ready",
      "Vibration",
      "Waterproof"
    ],
    "Style": [
      "Diamond grip",
      "Disposable",
      "Latex free",
      "Powder free",
      "Silicone free",
      "Sleeves"
    ]
  },
  "productMap": {
    "2LCTC": {
      "Brand": [
        "Coloursafe"
      ],
      "Coating": [
        "Crinkle Latex"
      ],
      "Cut Level": [
        "Cut 1"
      ],
      "Gauge": [
        "2 Stand Seamless"
      ],
      "Industry": [
        "Agriculture",
        "Construction",
        "Engineering",
        "Landscaping",
        "Scaffolding"
      ],
      "Liner Material": [
        "Polycotton Liner"
      ]
    },
    "BLACKPUPL": {
      "Brand": [
        "Coloursafe"
      ],
      "Coating": [
        "PU"
      ],
      "Cut Level": [
        "Cut 1",
        "Cut level A"
      ],
      "Gauge": [
        "13"
      ],
      "Industry": [
        "Agriculture",
        "Banksmen",
        "Construction",
        "General Handling",
        "Scaffolding",
        "Warehousing"
      ],
      "Liner Material": [
        "Polyester Liner"
      ],
      "Requirements": [
        "Vend Ready"
      ]
    },
    "BLACKPUPLVR": {
      "Brand": [
        "Coloursafe"
      ],
      "Coating": [
        "PU"
      ],
      "Cut Level": [
        "Cut 1",
        "Cut level A"
      ],
      "Gauge": [
        "13"
      ],
      "Industry": [
        "Agriculture",
        "Banksmen",
        "Construction",
        "General Handling",
        "Scaffolding",
        "Warehousing"
      ],
      "Liner Material": [
        "Polyester Liner"
      ],
      "Requirements": [
        "Vend Ready"
      ]
    },
    "CCMPP": {
      "Brand": [
        "Miscellaneous"
      ],
      "Coating": [
        "Leather"
      ],
      "Cut Level": [
        "Cut 1"
      ],
      "Gauge": [
        "8oz Cotton Drill"
      ],
      "Industry": [
        "Assembly",
        "Construction",
        "Gardening",
        "General Handling",
        "Packaging",
        "Warehousing"
      ],
      "Liner Material": [
        "100% Cotton"
      ]
    },
    "EZ324VR": {
      "Brand": [
        "Touchsafe"
      ],
      "Coating": [
        "Polymer"
      ],
      "Cut Level": [
        "Cut 1"
      ],
      "Gauge": [
        "18"
      ],
      "Industry": [
        "Food Industry"
      ],
      "Liner Material": [
        "Nylon Liner",
        "Spandex liner"
      ],
      "Requirements": [
        "Foodsafe",
        "Touchscreen",
        "Vend Ready"
      ]
    },
    "HAR2": {
      "Brand": [
        "Predator"
      ],
      "Coating": [
        "Leather"
      ],
      "Cut Level": [
        "Cut 2"
      ],
      "Industry": [
        "Agriculture",
        "Construction",
        "Foresty",
        "General Handling",
        "Metal work",
        "Scaffolding",
        "Warehousing"
      ],
      "Leather": [
        "Split Leather"
      ],
      "Liner Material": [
        "100% Cotton"
      ]
    },
    "HAWG2": {
      "Brand": [
        "Predator"
      ],
      "Coating": [
        "Leather"
      ],
      "Cut Level": [
        "Cut 2"
      ],
      "Industry": [
        "Arc Welding",
        "Construction",
        "Engineering",
        "Fabrication",
        "Metal work",
        "Mig Welding",
        "Welding"
      ],
      "Leather": [
        "Split Leather"
      ],
      "Liner Material": [
        "100% Cotton"
      ],
      "Requirements": [
        "Contact Heat"
      ]
    },
    "KDZGGO5": {
      "Brand": [
        "Miscellaneous"
      ],
      "Coating": [
        "TPE Palm Coating"
      ],
      "Gauge": [
        "13"
      ],
      "Industry": [
        "Gardening",
        "General Handling"
      ],
      "Liner Material": [
        "Polyester Liner",
        "Spandex liner"
      ],
      "Requirements": [
        "Minimal Risk"
      ]
    },
    "KDZGGY4": {
      "Brand": [
        "Miscellaneous"
      ],
      "Coating": [
        "TPE Palm Coating"
      ],
      "Industry": [
        "Gardening",
        "General Handling"
      ],
      "Liner Material": [
        "Polyester Liner",
        "Spandex liner"
      ],
      "Requirements": [
        "Minimal Risk"
      ]
    },
    "LCPLRED": {
      "Brand": [
        "Coloursafe"
      ],
      "Coating": [
        "Crinkle Latex"
      ],
      "Cut Level": [
        "Cut 1",
        "Cut level A"
      ],
      "Gauge": [
        "13"
      ],
      "Industry": [
        "Construction",
        "Engineering",
        "General Handling"
      ],
      "Liner Material": [
        "Polyester Liner"
      ]
    },
    "LCTCTD": {
      "Brand": [
        "Coloursafe"
      ],
      "Coating": [
        "Crinkle Latex"
      ],
      "Cut Level": [
        "Cut 1",
        "Cut level B"
      ],
      "Industry": [
        "Agriculture",
        "Banksmen",
        "Construction",
        "Engineering",
        "Scaffolding"
      ],
      "Liner Material": [
        "Polycotton Liner"
      ]
    },
    "MF15A": {
      "Brand": [
        "Touchsafe"
      ],
      "Coating": [
        "Nitrile Micro Foam"
      ],
      "Cut Level": [
        "Cut level A"
      ],
      "Gauge": [
        "15"
      ],
      "Industry": [
        "Construction",
        "Food Industry",
        "General Handling",
        "Landscaping",
        "Packaging",
        "Scaffolding",
        "Touchscreens",
        "Warehousing"
      ],
      "Liner Material": [
        "Nylon Liner",
        "Spandex liner"
      ],
      "Requirements": [
        "Contact Heat",
        "Touchscreen"
      ]
    },
    "NFPLR": {
      "Brand": [
        "Coloursafe"
      ],
      "Coating": [
        "Nitrile Foam"
      ],
      "Cut Level": [
        "Cut 1"
      ],
      "Gauge": [
        "13"
      ],
      "Industry": [
        "Agriculture",
        "Banksmen",
        "Construction",
        "General Handling",
        "Landscaping"
      ],
      "Liner Material": [
        "Polyester Liner"
      ],
      "Requirements": [
        "Contact Heat"
      ]
    },
    "NITGFL330": {
      "Brand": [
        "Nitrile"
      ],
      "Coating": [
        "Nitrile"
      ],
      "Cut Level": [
        "Cut 1"
      ],
      "Industry": [
        "Chemical",
        "Food Industry",
        "Janitorial",
        "Touchscreens"
      ],
      "Liner Material": [
        "Flock Lined"
      ],
      "Requirements": [
        "Foodsafe",
        "Touchscreen"
      ]
    },
    "NITKW": {
      "Cut Level": [
        "Cut 1"
      ],
      "Coating": [
        "Nitrile"
      ],
      "Requirements": [
        "Waterproof"
      ],
      "Industry": [
        "Banksmen",
        "Construction",
        "General Handling",
        "Packaging",
        "Scaffolding",
        "Warehousing"
      ],
      "Liner Material": [
        "Jersey Liner"
      ]
    },
    "NITSC": {
      "Brand": [
        "Miscellaneous"
      ],
      "Coating": [
        "Nitrile"
      ],
      "Cut Level": [
        "Cut 1"
      ],
      "Industry": [
        "Banksmen",
        "Construction",
        "General Handling",
        "Packaging",
        "Scaffolding",
        "Warehousing"
      ],
      "Liner Material": [
        "Jersey Liner"
      ]
    },
    "NSPL": {
      "Brand": [
        "Coloursafe"
      ],
      "Coating": [
        "Smooth Nitrile"
      ],
      "Cut Level": [
        "Cut 1",
        "Cut level A"
      ],
      "Gauge": [
        "13"
      ],
      "Industry": [
        "Agriculture",
        "Banksmen",
        "Construction",
        "Engineering",
        "General Handling",
        "Landscaping",
        "Scaffolding",
        "Warehousing"
      ],
      "Liner Material": [
        "Polyester Liner"
      ]
    },
    "PRED13VR": {
      "Brand": [
        "Touchsafe"
      ],
      "Coating": [
        "Sandy Nitrile"
      ],
      "Cut Level": [
        "Cut D"
      ],
      "Gauge": [
        "13"
      ],
      "Industry": [
        "Agriculture",
        "Construction",
        "Engineering",
        "Glass",
        "Glazing",
        "Metal work"
      ],
      "Liner Material": [
        "Polyethylene",
        "Spandex liner"
      ],
      "Requirements": [
        "Contact Heat",
        "Cut protection",
        "Touchscreen",
        "Vend Ready"
      ]
    },
    "PRED1": {
      "Brand": [
        "Predator"
      ],
      "Coating": [
        "Leather"
      ],
      "Cut Level": [
        "Cut 2"
      ],
      "Industry": [
        "Agriculture",
        "Construction",
        "Foresty",
        "General Handling",
        "Metal work",
        "Scaffolding",
        "Warehousing"
      ],
      "Leather": [
        "Split Leather"
      ],
      "Liner Material": [
        "100% Cotton"
      ]
    },
    "PRED1HV": {
      "Brand": [
        "Predator"
      ],
      "Coating": [
        "Leather"
      ],
      "Cut Level": [
        "Cut 2"
      ],
      "Industry": [
        "Agriculture",
        "Construction",
        "Foresty",
        "Rigging",
        "Scaffolding"
      ],
      "Leather": [
        "Split Leather"
      ],
      "Liner Material": [
        "100% Cotton"
      ]
    },
    "PRED12": {
      "Brand": [
        "Specialist"
      ],
      "Coating": [
        "Foam Latex"
      ],
      "Cut Level": [
        "Cut F"
      ],
      "Gauge": [
        "10"
      ],
      "Industry": [
        "Glass",
        "Glazing",
        "Metal work",
        "Needle Stick",
        "Recycling"
      ],
      "Liner Material": [
        "Polyester Liner",
        "Steel liner"
      ],
      "Requirements": [
        "Cut protection",
        "Needle Resistant",
        "Waterproof"
      ]
    },
    "PRED13": {
      "Brand": [
        "Coloursafe"
      ],
      "Coating": [
        "PU"
      ],
      "Cut Level": [
        "Cut F"
      ],
      "Gauge": [
        "13"
      ],
      "Industry": [
        "Agriculture",
        "Assembly",
        "Automotive",
        "Construction",
        "Engineering",
        "Fabrication",
        "Glass",
        "Sheet work"
      ],
      "Liner Material": [
        "Polyester Liner",
        "Spandex liner",
        "Steel liner"
      ],
      "Requirements": [
        "Cut protection",
        "Vend Ready"
      ]
    },
    "PRED16": {
      "Brand": [
        "Specialist"
      ],
      "Coating": [
        "Leather"
      ],
      "Cut Level": [
        "Cut 1"
      ],
      "Industry": [
        "Concrete Breakers",
        "Construction",
        "Engineering",
        "Mining"
      ],
      "Leather": [
        "Goat Skin"
      ],
      "Requirements": [
        "Anti Vibration",
        "Vibration"
      ]
    },
    "PRED2": {
      "Brand": [
        "Predator"
      ],
      "Coating": [
        "Leather"
      ],
      "Cut Level": [
        "Cut 1"
      ],
      "Industry": [
        "Agriculture",
        "Construction",
        "Foresty",
        "General Handling",
        "Metal work",
        "Scaffolding",
        "Warehousing"
      ],
      "Leather": [
        "Hide Leather"
      ],
      "Liner Material": [
        "100% Cotton"
      ]
    },
    "PRED2GOLD": {
      "Brand": [
        "Predator"
      ],
      "Coating": [
        "Leather"
      ],
      "Cut Level": [
        "Cut 1"
      ],
      "Industry": [
        "Agriculture",
        "Construction",
        "Foresty",
        "General Handling",
        "Metal work",
        "Scaffolding",
        "Warehousing"
      ],
      "Leather": [
        "Hide Leather"
      ],
      "Liner Material": [
        "100% Cotton"
      ]
    },
    "PRED315": {
      "Brand": [
        "Predator"
      ],
      "Coating": [
        "Leather"
      ],
      "Cut Level": [
        "Cut 1"
      ],
      "Industry": [
        "Agriculture",
        "Construction",
        "Foresty",
        "General Handling",
        "Logistics",
        "Scaffolding",
        "Warehousing"
      ],
      "Leather": [
        "Hide Leather"
      ],
      "Liner Material": [
        "100% Cotton"
      ]
    },
    "PRED3GOLD": {
      "Brand": [
        "Predator"
      ],
      "Coating": [
        "Leather"
      ],
      "Cut Level": [
        "Cut 1"
      ],
      "Industry": [
        "Agriculture",
        "Construction",
        "Foresty",
        "General Handling",
        "Logistics",
        "Rigging",
        "Scaffolding",
        "Warehousing"
      ],
      "Leather": [
        "Hide Leather"
      ],
      "Liner Material": [
        "100% Cotton"
      ]
    },
    "PRED3SB": {
      "Brand": [
        "Predator"
      ],
      "Coating": [
        "Leather"
      ],
      "Cut Level": [
        "Cut 1"
      ],
      "Industry": [
        "Agriculture",
        "Construction",
        "General Handling",
        "Rigging",
        "Scaffolding",
        "Warehousing"
      ],
      "Leather": [
        "Hide Leather"
      ],
      "Liner Material": [
        "100% Cotton"
      ]
    },
    "PRED4": {
      "Brand": [
        "Predator"
      ],
      "Coating": [
        "Leather"
      ],
      "Cut Level": [
        "Cut 2"
      ],
      "Industry": [
        "Arc Welding",
        "Construction",
        "Engineering",
        "Fabrication",
        "Metal work",
        "Mig Welding",
        "Welding"
      ],
      "Leather": [
        "Split Leather"
      ],
      "Liner Material": [
        "100% Cotton"
      ],
      "Requirements": [
        "Contact Heat"
      ]
    },
    "PRED416": {
      "Brand": [
        "Predator"
      ],
      "Coating": [
        "Leather"
      ],
      "Cut Level": [
        "Cut 2"
      ],
      "Industry": [
        "Arc Welding",
        "Construction",
        "Fabrication",
        "Forging",
        "Metal work",
        "Mig Welding",
        "Welding"
      ],
      "Leather": [
        "Split Leather"
      ],
      "Liner Material": [
        "100% Cotton"
      ],
      "Requirements": [
        "Contact Heat"
      ]
    },
    "PRED4GLOVE": {
      "Brand": [
        "Predator"
      ],
      "Coating": [
        "Leather"
      ],
      "Cut Level": [
        "Cut 1"
      ],
      "Industry": [
        "Construction",
        "Engineering",
        "Fabrication",
        "Forging",
        "Metal work"
      ],
      "Leather": [
        "Split Leather"
      ],
      "Liner Material": [
        "100% Cotton"
      ],
      "Requirements": [
        "Contact Heat"
      ]
    },
    "PRED4THORN": {
      "Brand": [
        "Specialist"
      ],
      "Coating": [
        "Leather"
      ],
      "Cut Level": [
        "Cut 2"
      ],
      "Industry": [
        "Foresty",
        "Gardening",
        "Landscaping"
      ],
      "Leather": [
        "Split Leather"
      ],
      "Liner Material": [
        "100% Cotton"
      ],
      "Requirements": [
        "Contact Heat",
        "Needle Resistant"
      ]
    },
    "PRED6": {
      "Brand": [
        "Predator"
      ],
      "Coating": [
        "Leather"
      ],
      "Cut Level": [
        "Cut 1"
      ],
      "Industry": [
        "Agriculture",
        "Construction",
        "Engineering",
        "Forging",
        "Metal work",
        "Tig Welding",
        "Welding"
      ],
      "Leather": [
        "Hide Leather"
      ],
      "Liner Material": [
        "100% Cotton"
      ],
      "Requirements": [
        "Contact Heat"
      ]
    },
    "PRED6C": {
      "Brand": [
        "Predator"
      ],
      "Coating": [
        "Leather"
      ],
      "Cut Level": [
        "Cut 1"
      ],
      "Industry": [
        "Agriculture",
        "Construction",
        "Engineering",
        "Forging",
        "Metal work",
        "Tig Welding",
        "Welding"
      ],
      "Leather": [
        "Hide Leather"
      ],
      "Liner Material": [
        "100% Cotton"
      ],
      "Requirements": [
        "Contact Heat"
      ]
    },
    "PRED6D": {
      "Brand": [
        "Predator"
      ],
      "Coating": [
        "Leather"
      ],
      "Cut Level": [
        "Cut 1"
      ],
      "Industry": [
        "Agriculture",
        "Construction",
        "Engineering",
        "Forging",
        "Metal work",
        "Tig Welding",
        "Welding"
      ],
      "Leather": [
        "Deer Hide"
      ],
      "Liner Material": [
        "100% Cotton"
      ],
      "Requirements": [
        "Contact Heat"
      ]
    },
    "PRED6GLOVE": {
      "Brand": [
        "Predator"
      ],
      "Coating": [
        "Leather"
      ],
      "Cut Level": [
        "Cut 1"
      ],
      "Industry": [
        "Agriculture",
        "Construction",
        "Engineering",
        "Forging",
        "Metal work"
      ],
      "Leather": [
        "Hide Leather"
      ],
      "Liner Material": [
        "100% Cotton"
      ],
      "Requirements": [
        "Contact Heat"
      ]
    },
    "PRKW10": {
      "Brand": [
        "Miscellaneous"
      ],
      "Coating": [
        "PVC"
      ],
      "Cut Level": [
        "Cut 1"
      ],
      "Industry": [
        "Assembly",
        "Construction",
        "Gardening",
        "General Handling",
        "Packaging",
        "Warehousing"
      ],
      "Liner Material": [
        "Jersey Liner",
        "Natural Cotton Liner"
      ]
    },
    "PU13D": {
      "Brand": [
        "Coloursafe"
      ],
      "Coating": [
        "PU"
      ],
      "Cut Level": [
        "Cut D"
      ],
      "Gauge": [
        "13"
      ],
      "Industry": [
        "Agriculture",
        "Construction",
        "Engineering",
        "General Handling",
        "Glass",
        "Landscaping",
        "Packaging",
        "Scaffolding",
        "Warehousing"
      ],
      "Liner Material": [
        "Polyester Liner",
        "Spandex liner",
        "UHMWPE"
      ],
      "Requirements": [
        "Cut protection"
      ]
    },
    "PUPL": {
      "Brand": [
        "Coloursafe"
      ],
      "Coating": [
        "PU"
      ],
      "Cut Level": [
        "Cut 1",
        "Cut level A"
      ],
      "Gauge": [
        "13"
      ],
      "Industry": [
        "Automotive",
        "Banksmen",
        "Construction",
        "Engineering",
        "General Handling",
        "Landscaping",
        "Scaffolding",
        "Warehousing"
      ],
      "Liner Material": [
        "Polyester Liner"
      ]
    },
    "PUUH13": {
      "Brand": [
        "Coloursafe"
      ],
      "Coating": [
        "PU"
      ],
      "Cut Level": [
        "Cut C"
      ],
      "Gauge": [
        "13"
      ],
      "Industry": [
        "Construction",
        "Engineering",
        "General Handling",
        "Landscaping",
        "Scaffolding"
      ],
      "Liner Material": [
        "Azura Liner",
        "Polyester Liner"
      ],
      "Requirements": [
        "Cut protection"
      ]
    },
    "RD300199Q": {
      "Brand": [
        "Nitrile"
      ],
      "Coating": [
        "Nitrile"
      ],
      "Industry": [
        "Food Industry",
        "Janitorial",
        "Plumbing",
        "Touchscreens",
        "Veterinary"
      ],
      "Requirements": [
        "Foodsafe",
        "Touchscreen",
        "Waterproof"
      ],
      "Style": [
        "Disposable",
        "Latex free",
        "Powder free",
        "Silicone free"
      ]
    },
    "RD3009600": {
      "Brand": [
        "Nitrile"
      ],
      "Coating": [
        "Nitrile"
      ],
      "Industry": [
        "Agriculture",
        "Asbestos",
        "Assembly",
        "Automotive",
        "Chemical",
        "Construction",
        "Food Industry",
        "Insulation",
        "Janitorial",
        "Plumbing",
        "Touchscreens",
        "Veterinary"
      ],
      "Requirements": [
        "Foodsafe",
        "Touchscreen",
        "Waterproof"
      ],
      "Style": [
        "Disposable",
        "Latex free",
        "Powder free",
        "Silicone free"
      ]
    },
    "RD301040Q": {
      "Brand": [
        "Nitrile"
      ],
      "Coating": [
        "Nitrile"
      ],
      "Industry": [
        "Asbestos",
        "Assembly",
        "Automotive",
        "Chemical",
        "Engineering",
        "Food Industry",
        "General Handling",
        "Insulation",
        "Janitorial",
        "Plumbing",
        "Touchscreens",
        "Veterinary"
      ],
      "Requirements": [
        "Foodsafe",
        "Touchscreen",
        "Waterproof"
      ],
      "Style": [
        "Disposable",
        "Latex free",
        "Powder free",
        "Silicone free"
      ]
    },
    "RD302370Q": {
      "Brand": [
        "Nitrile"
      ],
      "Coating": [
        "Nitrile"
      ],
      "Industry": [
        "Agriculture",
        "Asbestos",
        "Assembly",
        "Automotive",
        "Chemical",
        "Engineering",
        "Food Industry",
        "Insulation",
        "Janitorial",
        "Plumbing",
        "Touchscreens",
        "Veterinary"
      ],
      "Requirements": [
        "Foodsafe",
        "Touchscreen",
        "Waterproof"
      ],
      "Style": [
        "Disposable",
        "Latex free",
        "Powder free",
        "Silicone free"
      ]
    },
    "RD3029200": {
      "Brand": [
        "Nitrile"
      ],
      "Coating": [
        "Nitrile"
      ],
      "Industry": [
        "Agriculture",
        "Assembly",
        "Automotive",
        "Construction",
        "Insulation",
        "Janitorial",
        "Plumbing",
        "Veterinary"
      ],
      "Requirements": [
        "Foodsafe",
        "Touchscreen",
        "Waterproof"
      ],
      "Style": [
        "Disposable",
        "Latex free",
        "Powder free",
        "Silicone free"
      ]
    },
    "RP300146Q": {
      "Brand": [
        "Nitrile"
      ],
      "Coating": [
        "Nitrile"
      ],
      "Industry": [
        "Agriculture",
        "Assembly",
        "Automotive",
        "Construction",
        "Engineering",
        "Insulation",
        "Janitorial",
        "Plumbing",
        "Veterinary"
      ],
      "Requirements": [
        "Foodsafe",
        "Touchscreen",
        "Waterproof"
      ],
      "Style": [
        "Diamond grip",
        "Disposable",
        "Latex free",
        "Powder free",
        "Silicone free"
      ]
    },
    "RP300260Q": {
      "Brand": [
        "Nitrile"
      ],
      "Coating": [
        "Nitrile"
      ],
      "Industry": [
        "Asbestos",
        "Assembly",
        "Automotive",
        "Chemical",
        "Engineering",
        "Food Industry",
        "Insulation",
        "Janitorial",
        "Plumbing",
        "Touchscreens",
        "Veterinary"
      ],
      "Requirements": [
        "Foodsafe",
        "Touchscreen",
        "Waterproof"
      ],
      "Style": [
        "Diamond grip",
        "Disposable",
        "Latex free",
        "Powder free",
        "Silicone free"
      ]
    },
    "RP300270Q": {
      "Brand": [
        "Nitrile"
      ],
      "Coating": [
        "Nitrile"
      ],
      "Industry": [
        "Asbestos",
        "Assembly",
        "Chemical",
        "Food Industry",
        "Insulation",
        "Janitorial",
        "Plumbing",
        "Touchscreens",
        "Veterinary"
      ],
      "Requirements": [
        "Foodsafe",
        "Touchscreen",
        "Waterproof"
      ],
      "Style": [
        "Diamond grip",
        "Disposable",
        "Latex free",
        "Powder free",
        "Silicone free"
      ]
    },
    "RP300326Q": {
      "Brand": [
        "Nitrile"
      ],
      "Coating": [
        "Nitrile"
      ],
      "Industry": [
        "Agriculture",
        "Asbestos",
        "Assembly",
        "Automotive",
        "Chemical",
        "Construction",
        "Engineering",
        "Food Industry",
        "Insulation",
        "Janitorial",
        "Plumbing",
        "Touchscreens",
        "Veterinary"
      ],
      "Requirements": [
        "Foodsafe",
        "Touchscreen",
        "Waterproof"
      ],
      "Style": [
        "Diamond grip",
        "Disposable",
        "Latex free",
        "Powder free",
        "Silicone free"
      ]
    },
    "RP300376Q": {
      "Brand": [
        "Nitrile"
      ],
      "Coating": [
        "Nitrile"
      ],
      "Industry": [
        "Asbestos",
        "Assembly",
        "Automotive",
        "Chemical",
        "Engineering",
        "Food Industry",
        "General Handling",
        "Insulation",
        "Janitorial",
        "Plumbing",
        "Touchscreens",
        "Veterinary"
      ],
      "Requirements": [
        "Foodsafe",
        "Touchscreen",
        "Waterproof"
      ],
      "Style": [
        "Diamond grip",
        "Disposable",
        "Latex free",
        "Powder free",
        "Silicone free"
      ]
    },
    "RPET10DW": {
      "Brand": [
        "Planetsafe"
      ],
      "Coating": [
        "Foam Latex"
      ],
      "Cut Level": [
        "Cut D"
      ],
      "Gauge": [
        "10"
      ],
      "Industry": [
        "Automotive",
        "Cold stores",
        "Engineering",
        "Rigging",
        "Scaffolding",
        "Warehousing"
      ],
      "Liner Material": [
        "Metal Q",
        "Polyester Liner",
        "Recycled Polyester",
        "Spandex liner"
      ],
      "Requirements": [
        "Contact Heat",
        "Contact cold",
        "Cut protection",
        "Thermal"
      ]
    },
    "RPET15A": {
      "Brand": [
        "Planetsafe"
      ],
      "Coating": [
        "Nitrile Foam"
      ],
      "Cut Level": [
        "Cut 1"
      ],
      "Gauge": [
        "15"
      ],
      "Industry": [
        "Construction",
        "General Handling",
        "Landscaping",
        "Logistics",
        "Packaging",
        "Warehousing"
      ],
      "Liner Material": [
        "Polyester Liner",
        "Recycled Polyester"
      ],
      "Requirements": [
        "Contact Heat"
      ]
    },
    "RPET15E": {
      "Brand": [
        "Planetsafe"
      ],
      "Coating": [
        "Sandy Nitrile"
      ],
      "Cut Level": [
        "Cut E"
      ],
      "Gauge": [
        "15"
      ],
      "Industry": [
        "Agriculture",
        "Assembly",
        "Construction",
        "Engineering",
        "Fabrication",
        "Glass",
        "Glazing"
      ],
      "Liner Material": [
        "Metal Q",
        "Polyester Liner",
        "Recycled Polyester",
        "Spandex liner"
      ],
      "Requirements": [
        "Cut protection",
        "Touchscreen"
      ]
    },
    "RS1BVL": {
      "Brand": [
        "Predator"
      ],
      "Coating": [
        "Leather"
      ],
      "Cut Level": [
        "Cut 1"
      ],
      "Industry": [
        "Agriculture",
        "Construction",
        "Foresty",
        "Rigging",
        "Scaffolding",
        "Warehousing"
      ],
      "Leather": [
        "Split Leather"
      ],
      "Liner Material": [
        "100% Cotton"
      ]
    },
    "RS1CTH": {
      "Brand": [
        "Predator"
      ],
      "Coating": [
        "Leather"
      ],
      "Cut Level": [
        "Cut 1"
      ],
      "Industry": [
        "Cold stores",
        "Construction",
        "Logistics",
        "Rigging",
        "Scaffolding",
        "Warehousing"
      ],
      "Liner Material": [
        "Thinsulate Liner"
      ],
      "Requirements": [
        "Contact Heat",
        "Contact cold"
      ]
    },
    "RS2DPB": {
      "Brand": [
        "Predator"
      ],
      "Coating": [
        "Leather"
      ],
      "Cut Level": [
        "Cut 2"
      ],
      "Industry": [
        "Agriculture",
        "Construction",
        "Foresty",
        "General Handling",
        "Metal work",
        "Scaffolding",
        "Warehousing"
      ],
      "Leather": [
        "Split Leather"
      ],
      "Liner Material": [
        "100% Cotton"
      ],
      "Requirements": [
        "Contact Heat"
      ]
    },
    "RSW1C": {
      "Brand": [
        "Predator"
      ],
      "Coating": [
        "Leather"
      ],
      "Cut Level": [
        "Cut 1"
      ],
      "Industry": [
        "Arc Welding",
        "Construction",
        "Engineering",
        "Fabrication",
        "Metal work",
        "Mig Welding",
        "Welding"
      ],
      "Leather": [
        "Split Leather"
      ],
      "Liner Material": [
        "100% Cotton"
      ],
      "Requirements": [
        "Contact Heat"
      ]
    },
    "RSW1CBLUE": {
      "Brand": [
        "Predator"
      ],
      "Coating": [
        "Leather"
      ],
      "Cut Level": [
        "Cut 1"
      ],
      "Industry": [
        "Arc Welding",
        "Construction",
        "Engineering",
        "Fabrication",
        "Forging",
        "Mig Welding",
        "Welding"
      ],
      "Leather": [
        "Split Leather"
      ],
      "Liner Material": [
        "100% Cotton"
      ],
      "Requirements": [
        "Contact Heat"
      ]
    },
    "RSW1CBLUES": {
      "Brand": [
        "Predator"
      ],
      "Coating": [
        "Leather"
      ],
      "Cut Level": [
        "Cut 1"
      ],
      "Industry": [
        "Arc Welding",
        "Construction",
        "Engineering",
        "Fabrication",
        "Forging",
        "Mig Welding"
      ],
      "Leather": [
        "Split Leather"
      ],
      "Liner Material": [
        "100% Cotton"
      ],
      "Requirements": [
        "Contact Heat"
      ]
    },
    "RSW1CKEV": {
      "Brand": [
        "Predator"
      ],
      "Coating": [
        "Leather"
      ],
      "Cut Level": [
        "Cut 1"
      ],
      "Industry": [
        "Arc Welding",
        "Construction",
        "Engineering",
        "Fabrication",
        "Metal work",
        "Mig Welding",
        "Welding"
      ],
      "Leather": [
        "Split Leather"
      ],
      "Liner Material": [
        "100% Cotton"
      ],
      "Requirements": [
        "Contact Heat"
      ]
    },
    "RSW1CREV": {
      "Brand": [
        "Predator"
      ],
      "Coating": [
        "Leather"
      ],
      "Cut Level": [
        "Cut 1"
      ],
      "Industry": [
        "Arc Welding",
        "Construction",
        "Engineering",
        "Fabrication",
        "Metal work",
        "Mig Welding"
      ],
      "Leather": [
        "Split Leather"
      ],
      "Liner Material": [
        "100% Cotton"
      ],
      "Requirements": [
        "Contact Heat"
      ]
    },
    "SL1HRF": {
      "Brand": [
        "Miscellaneous"
      ],
      "Cut Level": [
        "Cut F"
      ],
      "Gauge": [
        "18"
      ],
      "Industry": [
        "Agriculture",
        "Automotive",
        "Engineering",
        "Sheet work"
      ],
      "Liner Material": [
        "Nylon Liner",
        "Polyester Liner",
        "Spandex liner"
      ],
      "Requirements": [
        "Contact Heat",
        "Cut protection"
      ],
      "Style": [
        "Sleeves"
      ]
    },
    "SL2CLD": {
      "Brand": [
        "Miscellaneous"
      ],
      "Cut Level": [
        "Cut D"
      ],
      "Gauge": [
        "18"
      ],
      "Industry": [
        "Agriculture",
        "Automotive",
        "Engineering",
        "Sheet work"
      ],
      "Liner Material": [
        "Metal Q",
        "Spandex liner"
      ],
      "Requirements": [
        "Cut protection"
      ],
      "Style": [
        "Sleeves"
      ]
    },
    "SL3VIPD": {
      "Brand": [
        "Miscellaneous"
      ],
      "Cut Level": [
        "Cut D"
      ],
      "Gauge": [
        "13"
      ],
      "Industry": [
        "Agriculture",
        "Automotive",
        "Engineering",
        "Sheet work"
      ],
      "Liner Material": [
        "Nylon Liner",
        "Spandex liner"
      ],
      "Requirements": [
        "Cut protection"
      ],
      "Style": [
        "Sleeves"
      ]
    },
    "SN13DTQ": {
      "Brand": [
        "Touchsafe"
      ],
      "Coating": [
        "Sandy Nitrile"
      ],
      "Cut Level": [
        "Cut D"
      ],
      "Gauge": [
        "13"
      ],
      "Industry": [
        "Agriculture",
        "Construction",
        "Food Industry",
        "Glass",
        "Glazing",
        "Landscaping",
        "Metal work",
        "Packaging",
        "Scaffolding",
        "Touchscreens",
        "Warehousing"
      ],
      "Liner Material": [
        "Polyethylene",
        "Spandex liner",
        "UHMWPE"
      ],
      "Requirements": [
        "Contact Heat",
        "Cut protection",
        "Touchscreen",
        "Vend Ready"
      ]
    },
    "SN13DTQVR": {
      "Brand": [
        "Touchsafe"
      ],
      "Coating": [
        "Sandy Nitrile"
      ],
      "Cut Level": [
        "Cut D"
      ],
      "Gauge": [
        "13"
      ],
      "Industry": [
        "Agriculture",
        "Construction",
        "Engineering",
        "Glass",
        "Glazing",
        "Metal work"
      ],
      "Liner Material": [
        "Polyethylene",
        "Spandex liner"
      ],
      "Requirements": [
        "Contact Heat",
        "Touchscreen",
        "Vend Ready"
      ]
    },
    "STLKW": {
      "Brand": [
        "Miscellaneous"
      ],
      "Industry": [
        "Assembly",
        "General Handling",
        "Inspection",
        "Packaging",
        "Warehousing"
      ],
      "Liner Material": [
        "100% Cotton"
      ],
      "Requirements": [
        "Minimal Risk"
      ]
    },
    "STMKW": {
      "Brand": [
        "Miscellaneous"
      ],
      "Industry": [
        "Assembly",
        "General Handling",
        "Inspection",
        "Packaging",
        "Warehousing"
      ],
      "Liner Material": [
        "100% Cotton"
      ],
      "Requirements": [
        "Minimal Risk"
      ]
    },
    "TS1": {
      "Brand": [
        "Touchsafe"
      ],
      "Coating": [
        "Polymax"
      ],
      "Cut Level": [
        "Cut 1"
      ],
      "Gauge": [
        "15"
      ],
      "Industry": [
        "Assembly",
        "Automotive",
        "Engineering",
        "Food Industry",
        "Touchscreens"
      ],
      "Liner Material": [
        "Nylon Liner",
        "Spandex liner"
      ],
      "Requirements": [
        "Contact Heat",
        "Foodsafe",
        "Touchscreen"
      ]
    },
    "TS4": {
      "Brand": [
        "Touchsafe"
      ],
      "Coating": [
        "Polymax"
      ],
      "Cut Level": [
        "Cut F"
      ],
      "Gauge": [
        "18"
      ],
      "Industry": [
        "Automotive",
        "Fabrication",
        "Food Industry",
        "Glass",
        "Glazing",
        "Metal work",
        "Touchscreens"
      ],
      "Liner Material": [
        "Nylon Liner",
        "Spandex liner",
        "Tekarmor"
      ],
      "Requirements": [
        "Contact Heat",
        "Cut protection",
        "Foodsafe",
        "Impact",
        "Touchscreen"
      ]
    },
    "WPTL7CL": {
      "Brand": [
        "Coloursafe"
      ],
      "Coating": [
        "Crinkle Latex"
      ],
      "Cut Level": [
        "Cut 1"
      ],
      "Gauge": [
        "7"
      ],
      "Industry": [
        "Agriculture",
        "Banksmen",
        "Cold stores",
        "Construction",
        "Engineering",
        "Scaffolding"
      ],
      "Liner Material": [
        "Polyester Liner"
      ],
      "Requirements": [
        "Contact cold",
        "Thermal"
      ]
    },
    "WS1": {
      "Brand": [
        "Watersafe"
      ],
      "Coating": [
        "Latex"
      ],
      "Cut Level": [
        "Cut 1"
      ],
      "Gauge": [
        "15"
      ],
      "Industry": [
        "Banksmen",
        "Construction",
        "Engineering",
        "General Handling",
        "Landscaping",
        "Scaffolding"
      ],
      "Liner Material": [
        "Nylon Liner",
        "Spandex liner"
      ],
      "Requirements": [
        "Contact Heat",
        "Waterproof"
      ]
    },
    "WS4": {
      "Brand": [
        "Watersafe"
      ],
      "Coating": [
        "Latex"
      ],
      "Cut Level": [
        "Cut 2",
        "Cut level B"
      ],
      "Gauge": [
        "15"
      ],
      "Industry": [
        "Cold stores",
        "Construction",
        "Engineering",
        "Landscaping",
        "Logistics",
        "Scaffolding"
      ],
      "Liner Material": [
        "Acrylic liner",
        "Polyester Liner"
      ],
      "Requirements": [
        "Contact Heat",
        "Contact cold",
        "Waterproof"
      ]
    },
    "WS5": {
      "Brand": [
        "Watersafe"
      ],
      "Coating": [
        "Sandy Nitrile"
      ],
      "Cut Level": [
        "Cut E"
      ],
      "Gauge": [
        "13"
      ],
      "Industry": [
        "Cold stores",
        "Construction",
        "Engineering",
        "Metal work",
        "Recycling",
        "Waste Management"
      ],
      "Liner Material": [
        "Acrylic liner",
        "Polyester Liner",
        "Steel liner"
      ],
      "Requirements": [
        "Contact Heat",
        "Contact cold",
        "Thermal",
        "Waterproof"
      ]
    },
    "WS6": {
      "Brand": [
        "Watersafe"
      ],
      "Coating": [
        "Crinkle Latex"
      ],
      "Cut Level": [
        "Cut 1"
      ],
      "Gauge": [
        "7"
      ],
      "Industry": [
        "Banksmen",
        "Construction",
        "Engineering",
        "General Handling",
        "Landscaping",
        "Scaffolding"
      ],
      "Liner Material": [
        "Polyester Liner"
      ],
      "Requirements": [
        "Waterproof"
      ]
    },
    "WS7": {
      "Brand": [
        "Watersafe"
      ],
      "Coating": [
        "Latex"
      ],
      "Cut Level": [
        "Cut E"
      ],
      "Gauge": [
        "15"
      ],
      "Industry": [
        "Cold stores",
        "Construction",
        "Engineering",
        "General Handling",
        "Glass",
        "Recycling",
        "Waste Management"
      ],
      "Liner Material": [
        "Polyester Liner",
        "Steel liner"
      ],
      "Requirements": [
        "Contact cold",
        "Cut protection",
        "Thermal",
        "Waterproof"
      ]
    },
    "WS8": {
      "Brand": [
        "Watersafe"
      ],
      "Coating": [
        "Sandy Nitrile"
      ],
      "Cut Level": [
        "Cut 1"
      ],
      "Gauge": [
        "15"
      ],
      "Industry": [
        "Cold stores",
        "Construction",
        "Engineering",
        "General Handling",
        "Landscaping",
        "Scaffolding"
      ],
      "Liner Material": [
        "Nylon Liner"
      ],
      "Requirements": [
        "Contact Heat",
        "Waterproof"
      ]
    },
    "WS9": {
      "Brand": [
        "Watersafe"
      ],
      "Coating": [
        "Sandy Nitrile"
      ],
      "Cut Level": [
        "Cut F"
      ],
      "Gauge": [
        "13"
      ],
      "Industry": [
        "Banksmen",
        "Engineering",
        "Glass",
        "Recycling"
      ],
      "Liner Material": [
        "Nylon Liner",
        "Spandex liner",
        "Steel liner"
      ],
      "Requirements": [
        "Contact Heat",
        "Cut protection",
        "Waterproof"
      ]
    }
  },
  "featureCategories": [
    "Coating",
    "Cut Level",
    "Liner Material",
    "Requirements",
    "Style",
    "Leather",
    "Gauge"
  ]
};
