// Auto-generated by Glove Admin on 2026-01-06T09:15:51.648Z

window.GLOVES = 
[
  {
    "code": "2-LCTC",
    "name": "Amber",
    "brand": "Coloursafe",
    "sizes": "7 - 11",
    "image": "Images/2-LCTC.jpg",
    "datasheet": "Datasheets/2-LCTC.pdf",
    "gauge": "13",
    "coating": "Crinkle Latex",
    "liner": "Polycotton Liner",
    "cutLevel": "Cut 1",
    "industries": [
      "Agriculture",
      "Construction",
      "Engineering",
      "Landscaping",
      "Scaffolding"
    ]
  },
  {
    "code": "BLACKPUPL",
    "name": "Jet",
    "brand": "Coloursafe",
    "sizes": "6 - 11",
    "image": "Images/BLACK-PUPL.jpg",
    "datasheet": "Datasheets/BLACK-PUPL.pdf",
    "gauge": "13",
    "coating": "PU",
    "liner": "Polyester Liner",
    "cutLevel": "Cut 1",
    "requirementsList": [
      "Vend Ready"
    ],
    "industries": [
      "Agriculture",
      "Banksmen",
      "Construction",
      "General Handling",
      "Scaffolding",
      "Warehousing"
    ]
  },
  {
    "code": "CCMPP",
    "name": "Cotton Chrome",
    "brand": "Coloursafe",
    "sizes": "10",
    "image": "Images/CCMPP.jpg",
    "datasheet": "Datasheets/CCMPP.pdf",
    "gauge": "8oz Cotton Drill",
    "coating": "Leather",
    "liner": "100% Cotton",
    "cutLevel": "Cut 1",
    "industries": [
      "Assembly",
      "Construction",
      "Gardening",
      "General Handling",
      "Packaging",
      "Warehousing"
    ]
  },
  {
    "code": "EZ-324-VR",
    "name": "Ez-Grip",
    "brand": "Touchsafe",
    "sizes": "6 - 11",
    "image": "Images/EZ-324-VR.jpg",
    "datasheet": "Datasheets/EZ-324-VR.pdf",
    "gauge": "18",
    "coating": "Polymer",
    "liner": "Nylon Liner",
    "cutLevel": "Cut 1",
    "style": [
      "Diamond grip",
      "Disposable"
    ],
    "requirementsList": [
      "Foodsafe",
      "Touchscreen",
      "Vend Ready"
    ],
    "industries": [
      "Arc Welding",
      "Asbestos"
    ]
  },
  {
    "code": "HAR2",
    "name": "Force",
    "brand": "Rigger Gloves",
    "sizes": "10",
    "image": "Images/HAR2.jpg",
    "datasheet": "Datasheets/HAR2.pdf",
    "leather": "Split Leather",
    "liner": "100% Cotton",
    "cutLevel": "Cut 2",
    "industries": [
      "Agriculture",
      "Construction",
      "Foresty",
      "General Handling",
      "Metal work",
      "Scaffolding",
      "Warehousing"
    ]
  },
  {
    "code": "HAWG2",
    "name": "Thunder Red Mig",
    "brand": "Mig Gauntlets",
    "sizes": "11",
    "image": "Images/HAWG2.jpg",
    "datasheet": "Datasheets/HAWG2.pdf",
    "leather": "Split Leather",
    "liner": "100% Cotton",
    "cutLevel": "Cut 2",
    "requirementsList": [
      "Contact Heat"
    ],
    "industries": [
      "Arc Welding",
      "Engineering",
      "Metal work",
      "Mig Welding",
      "Construction",
      "Fabrication"
    ]
  },
  {
    "code": "LCPL-RED",
    "name": "Fire",
    "brand": "Coloursafe",
    "sizes": "6 - 11",
    "image": "Images/LCPL-RED.jpg",
    "datasheet": "Datasheets/LCPL-RED.pdf",
    "gauge": "13",
    "coating": "Crinkle Latex",
    "liner": "Polyester Liner",
    "cutLevel": "Cut 1",
    "style": [
      "Latex free"
    ],
    "industries": [
      "Construction",
      "Engineering",
      "General Handling"
    ]
  },
  {
    "code": "LCTC-TD",
    "name": "Paws",
    "brand": "Coloursafe",
    "sizes": "7 - 11",
    "image": "Images/LCTC-TD.jpg",
    "datasheet": "Datasheets/LCTC-TD.pdf",
    "coating": "Latex",
    "liner": "Polycotton Liner",
    "cutLevel": "Cut level B",
    "industries": [
      "Agriculture",
      "Banksmen",
      "Construction",
      "Engineering",
      "Scaffolding"
    ]
  },
  {
    "code": "MF15A",
    "name": "Graphite",
    "brand": "Touchsafe",
    "sizes": "6 - 11",
    "image": "Images/MF15A.jpg",
    "datasheet": "Datasheets/MF15A.pdf",
    "gauge": "15",
    "coating": "Nitrile Micro Foam",
    "liner": "Nylon Liner",
    "cutLevel": "Cut level A",
    "requirementsList": [
      "Contact Heat",
      "Touchscreen"
    ],
    "industries": [
      "Construction",
      "Food Industry",
      "General Handling",
      "Landscaping",
      "Packaging",
      "Scaffolding",
      "Touchscreens",
      "Warehousing"
    ]
  },
  {
    "code": "NFPL-R",
    "name": "Cardinal",
    "brand": "Coloursafe",
    "sizes": "8 - 11",
    "image": "Images/NFPL-R.jpg",
    "datasheet": "Datasheets/NFPL-R.pdf",
    "gauge": "13",
    "coating": "Nitrile Foam",
    "liner": "Polyester Liner",
    "cutLevel": "Cut 1",
    "requirementsList": [
      "Contact Heat"
    ],
    "industries": [
      "Agriculture",
      "Banksmen",
      "Construction",
      "General Handling",
      "Landscaping"
    ]
  },
  {
    "code": "NITGFL330",
    "name": "Boron",
    "brand": "Mercator",
    "sizes": "S - 2XL",
    "image": "Images/NITGFL330.jpg",
    "datasheet": "Datasheets/NITGFL330.pdf",
    "coating": "Nitrile",
    "liner": "Flock Lined",
    "cutLevel": "Cut 1",
    "requirementsList": [
      "Foodsafe",
      "Touchscreen"
    ],
    "industries": [
      "Chemical",
      "Food Industry",
      "Janitorial",
      "Touchscreens"
    ]
  },
  {
    "code": "NITKW",
    "name": "Krypton (Knit-Wrist)",
    "brand": "Miscellaneous",
    "sizes": "8 - 11",
    "image": "Images/NITKW.jpg",
    "datasheet": "Datasheets/NITKW.pdf",
    "coating": "Nitrile",
    "liner": "Jersey Liner",
    "cutLevel": "Cut 1",
    "requirementsList": [
      "Waterproof"
    ],
    "industries": [
      "Banksmen",
      "Construction",
      "General Handling",
      "Packaging",
      "Scaffolding",
      "Warehousing"
    ]
  },
  {
    "code": "NITSC",
    "name": "Radon (Safety Cuff)",
    "brand": "Miscellaneous",
    "sizes": "10",
    "image": "Images/NITSC.jpg",
    "datasheet": "Datasheets/NITSC.pdf",
    "coating": "Nitrile",
    "liner": "Jersey Liner",
    "cutLevel": "Cut 1",
    "industries": [
      "Banksmen",
      "Construction",
      "General Handling",
      "Packaging",
      "Scaffolding",
      "Warehousing"
    ]
  },
  {
    "code": "NSPL",
    "name": "Scarlet",
    "brand": "Coloursafe",
    "sizes": "7 - 11",
    "image": "Images/NSPL.jpg",
    "datasheet": "Datasheets/NSPL.pdf",
    "gauge": "13",
    "coating": "Smooth Nitrile",
    "liner": "Polyester Liner",
    "cutLevel": "Cut 1",
    "industries": [
      "Banksmen",
      "Construction",
      "Engineering",
      "General Handling",
      "Landscaping",
      "Scaffolding",
      "Warehousing",
      "Agriculture"
    ]
  },
  {
    "code": "PRED1",
    "name": "Tiger",
    "brand": "Predator",
    "sizes": "10",
    "image": "Images/PRED1.jpg",
    "datasheet": "Datasheets/PRED1.pdf",
    "leather": "Split Leather",
    "liner": "100% Cotton",
    "cutLevel": "Cut 2",
    "industries": [
      "Agriculture",
      "Construction",
      "Foresty",
      "General Handling",
      "Metal work",
      "Scaffolding",
      "Warehousing"
    ]
  },
  {
    "code": "PRED1-HV",
    "name": "Hi-Vis Tiger",
    "brand": "Predator",
    "sizes": "10",
    "image": "Images/PRED1-HV.jpg",
    "datasheet": "Datasheets/PRED1-HV.pdf",
    "leather": "Split Leather",
    "liner": "100% Cotton",
    "cutLevel": "Cut 2",
    "industries": [
      "Agriculture",
      "Construction",
      "Foresty",
      "Rigging",
      "Scaffolding"
    ]
  },
  {
    "code": "PRED12",
    "name": "Needle",
    "brand": "Specialist",
    "sizes": "8 - 11",
    "image": "Images/PRED12.jpg",
    "datasheet": "Datasheets/PRED12.pdf",
    "gauge": "10",
    "coating": "Foam Latex",
    "cutLevel": "Cut F",
    "requirementsList": [
      "Cut protection",
      "Needle",
      "Needle Resistant",
      "Waterproof"
    ],
    "industries": [
      "Glass",
      "Glazing",
      "Metal work",
      "Needle Stick",
      "Recycling"
    ]
  },
  {
    "code": "PRED13",
    "name": "Sapphire",
    "brand": "Coloursafe",
    "sizes": "7 - 11",
    "image": "Images/PRED13.jpg",
    "datasheet": "Datasheets/PRED13.pdf",
    "gauge": "13",
    "coating": "PU",
    "liner": "Polyester Liner",
    "cutLevel": "Cut F",
    "requirementsList": [
      "Cut protection",
      "Vend Ready"
    ],
    "industries": [
      "Agriculture",
      "Assembly",
      "Automotive",
      "Construction",
      "Engineering",
      "Fabrication",
      "Glass",
      "Sheet work"
    ]
  },
  {
    "code": "PRED16",
    "name": "Anti-Vibe",
    "brand": "Specialist",
    "sizes": "7 - 11",
    "image": "Images/PRED16.jpg",
    "datasheet": "Datasheets/PRED16.pdf",
    "leather": "Goat Skin",
    "cutLevel": "Cut 1",
    "requirementsList": [
      "Anti Vibration"
    ],
    "industries": [
      "Concrete Breakers",
      "Construction",
      "Engineering",
      "Mining"
    ]
  },
  {
    "code": "PRED2",
    "name": "Hide Rigger Ivory",
    "brand": "Predator",
    "sizes": "10",
    "image": "Images/PRED2.jpg",
    "datasheet": "Datasheets/PRED2.pdf",
    "leather": "Hide Leather",
    "liner": "100% Cotton",
    "cutLevel": "Cut 1",
    "industries": [
      "Agriculture",
      "Construction",
      "Foresty",
      "General Handling",
      "Metal work",
      "Scaffolding",
      "Warehousing",
      "Work gloves"
    ]
  },
  {
    "code": "PRED2-GOLD",
    "name": "Hide Rigger Gold",
    "brand": "Predator",
    "sizes": "10",
    "image": "Images/PRED2-GOLD.jpg",
    "datasheet": "Datasheets/PRED2-GOLD.pdf",
    "leather": "Hide Leather",
    "liner": "100% Cotton",
    "cutLevel": "Cut 1",
    "industries": [
      "Agriculture",
      "Construction",
      "Foresty",
      "General Handling",
      "Metal work",
      "Scaffolding",
      "Warehousing",
      "Work gloves"
    ]
  },
  {
    "code": "PRED3-15",
    "name": "Ivory Drivers Glove",
    "brand": "Predator",
    "sizes": "10",
    "image": "Images/PRED3-15.jpg",
    "datasheet": "Datasheets/PRED3-15.pdf",
    "leather": "Hide Leather",
    "liner": "100% Cotton",
    "cutLevel": "Cut 1",
    "industries": [
      "Agriculture",
      "Construction",
      "Foresty",
      "General Handling",
      "Logistics",
      "Scaffolding",
      "Warehousing"
    ]
  },
  {
    "code": "PRED3-GOLD",
    "name": "Gold Drivers Glove",
    "brand": "Predator",
    "sizes": "10",
    "image": "Images/PRED3-GOLD.jpg",
    "datasheet": "Datasheets/PRED3-GOLD.pdf",
    "leather": "Hide Leather",
    "liner": "100% Cotton",
    "cutLevel": "Cut 1",
    "industries": [
      "Agriculture",
      "Construction",
      "General Handling",
      "Logistics",
      "Rigging",
      "Warehousing",
      "Foresty",
      "Scaffolding"
    ]
  },
  {
    "code": "PRED3-SB",
    "name": "Standard Driver",
    "brand": "Predator",
    "sizes": "10",
    "image": "Images/PRED3-SB.jpg",
    "datasheet": "Datasheets/PRED3-SB.pdf",
    "leather": "Hide Leather",
    "liner": "100% Cotton",
    "cutLevel": "Cut 1",
    "industries": [
      "Agriculture",
      "Construction",
      "General Handling",
      "Rigging",
      "Scaffolding",
      "Warehousing"
    ]
  },
  {
    "code": "PRED4",
    "name": "Signature Mig Gauntlet",
    "brand": "Predator",
    "sizes": "11",
    "image": "Images/PRED4.jpg",
    "datasheet": "Datasheets/PRED4.pdf",
    "leather": "Split Leather",
    "liner": "100% Cotton",
    "cutLevel": "Cut 2",
    "requirementsList": [
      "Contact Heat"
    ],
    "industries": [
      "Arc Welding",
      "Construction",
      "Engineering",
      "Fabrication",
      "Metal work",
      "Mig Welding",
      "Welding"
    ]
  },
  {
    "code": "PRED4-16",
    "name": "Signature 16\" Mig Gauntlet",
    "brand": "Predator",
    "sizes": "11",
    "image": "Images/PRED4-16.jpg",
    "datasheet": "Datasheets/PRED4-16.pdf",
    "leather": "Split Leather",
    "liner": "100% Cotton",
    "cutLevel": "Cut 2",
    "requirementsList": [
      "Contact Heat"
    ],
    "industries": [
      "Arc Welding",
      "Construction",
      "Fabrication",
      "Forging",
      "Metal work",
      "Mig Welding"
    ]
  },
  {
    "code": "PRED4-GLOVE",
    "name": "Mig Glove",
    "brand": "Predator",
    "sizes": "10",
    "image": "Images/PRED4-GLOVE.jpg",
    "datasheet": "Datasheets/PRED4-GLOVE.pdf",
    "leather": "Split Leather",
    "liner": "100% Cotton",
    "cutLevel": "Cut 1",
    "requirementsList": [
      "Contact Heat"
    ],
    "industries": [
      "Construction",
      "Engineering",
      "Forging",
      "Fabrication",
      "Metal work"
    ]
  },
  {
    "code": "PRED4-THORN",
    "name": "Thornproof",
    "brand": "Specialist",
    "sizes": "11",
    "image": "Images/PRED4-THORN.jpg",
    "datasheet": "Datasheets/PRED4-THORN.pdf",
    "leather": "Split Leather",
    "liner": "100% Cotton",
    "cutLevel": "Cut 2",
    "requirementsList": [
      "Contact Heat",
      "Needle Resistant"
    ],
    "industries": [
      "Gardening",
      "Foresty",
      "Landscaping"
    ]
  },
  {
    "code": "PRED6",
    "name": "Signature Tig",
    "brand": "Predator",
    "sizes": "10",
    "image": "Images/PRED6.jpg",
    "datasheet": "Datasheets/PRED6.pdf",
    "leather": "Hide Leather",
    "liner": "100% Cotton",
    "cutLevel": "Cut 1",
    "requirementsList": [
      "Contact Heat"
    ],
    "industries": [
      "Agriculture",
      "Construction",
      "Engineering",
      "Forging",
      "Metal work",
      "Tig Welding",
      "Welding"
    ]
  },
  {
    "code": "PRED6-C",
    "name": "Standard Tig",
    "brand": "Predator",
    "sizes": "10",
    "image": "Images/PRED6-C.jpg",
    "datasheet": "Datasheets/PRED6-C.pdf",
    "leather": "Hide Leather",
    "liner": "100% Cotton",
    "cutLevel": "Cut 1",
    "requirementsList": [
      "Contact Heat"
    ],
    "industries": [
      "Agriculture",
      "Construction",
      "Engineering",
      "Forging",
      "Metal work",
      "Tig Welding"
    ]
  },
  {
    "code": "PRED6-D",
    "name": "Deerskin Tig",
    "brand": "Predator",
    "sizes": "10",
    "image": "Images/PRED6-D.jpg",
    "datasheet": "Datasheets/PRED6-D.pdf",
    "leather": "Deer Hide",
    "liner": "100% Cotton",
    "cutLevel": "Cut 1",
    "requirementsList": [
      "Contact Heat"
    ],
    "industries": [
      "Agriculture",
      "Construction",
      "Engineering",
      "Forging",
      "Tig Welding",
      "Metal work"
    ]
  },
  {
    "code": "PRED6-GLOVE",
    "name": "Tig Glove",
    "brand": "Predator",
    "sizes": "10",
    "image": "Images/PRED6-GLOVE.jpg",
    "datasheet": "Datasheets/PRED6-GLOVE.pdf",
    "leather": "Hide Leather",
    "liner": "100% Cotton",
    "cutLevel": "Cut 1",
    "requirementsList": [
      "Contact Heat"
    ],
    "industries": [
      "Agriculture",
      "Construction",
      "Engineering",
      "Forging",
      "Metal work",
      "Tig Welding"
    ]
  },
  {
    "code": "PRKW-10",
    "name": "PVC Knit Wrist",
    "brand": "Miscellaneous",
    "sizes": "10",
    "image": "Images/PRKW-10.jpg",
    "datasheet": "Datasheets/PRKW-10.pdf",
    "coating": "PVC",
    "liner": "Natural Cotton Liner",
    "cutLevel": "Cut 1",
    "industries": [
      "Assembly",
      "Construction",
      "Gardening",
      "General Handling",
      "Packaging",
      "Warehousing"
    ]
  },
  {
    "code": "PU13D",
    "name": "Delta",
    "brand": "Coloursafe",
    "sizes": "6 - 11",
    "image": "Images/PUU13D.jpg",
    "datasheet": "Datasheets/PUU13D.pdf",
    "gauge": "13",
    "coating": "PU",
    "liner": "Polyester Liner",
    "cutLevel": "Cut D",
    "requirementsList": [
      "Cut protection"
    ],
    "industries": [
      "Agriculture",
      "Construction",
      "Engineering",
      "General Handling",
      "Glass",
      "Landscaping",
      "Packaging",
      "Scaffolding",
      "Warehousing"
    ]
  },
  {
    "code": "PUPL",
    "name": "Ruby",
    "brand": "Coloursafe",
    "sizes": "7 - 11",
    "image": "Images/PUPL.jpg",
    "datasheet": "Datasheets/PUPL.pdf",
    "gauge": "13",
    "coating": "PU",
    "liner": "Polyester Liner",
    "cutLevel": "Cut 1",
    "industries": [
      "Automotive",
      "Banksmen",
      "Construction",
      "Engineering",
      "General Handling",
      "Landscaping",
      "Scaffolding",
      "Warehousing"
    ]
  },
  {
    "code": "PUUH-13",
    "name": "Emerald",
    "brand": "Coloursafe",
    "sizes": "7 - 11",
    "image": "Images/PUUH-13.jpg",
    "datasheet": "Datasheets/PUUH-13.pdf",
    "gauge": "13",
    "coating": "PU",
    "liner": "Azura Liner",
    "cutLevel": "Cut C",
    "requirementsList": [
      "Cut protection"
    ],
    "industries": [
      "Construction",
      "Engineering",
      "General Handling",
      "Landscaping",
      "Scaffolding"
    ]
  },
  {
    "code": "RD300199Q",
    "name": "Nitrylex Classic Blue",
    "brand": "Mercator",
    "sizes": "S - 2XL",
    "image": "Images/RD3001990.jpg",
    "datasheet": "Datasheets/RD3001990.pdf",
    "coating": "Nitrile",
    "style": [
      "Diamond grip",
      "Disposable",
      "Latex free",
      "Powder free",
      "Silicone free"
    ],
    "requirementsList": [
      "Foodsafe",
      "Touchscreen"
    ],
    "industries": [
      "Food Industry",
      "Touchscreens"
    ]
  },
  {
    "code": "RD3009600",
    "name": "Nitrylex Classic Blue (200's)",
    "brand": "Mercator",
    "sizes": "s - 2XL",
    "image": "Images/RD3009600.jpg",
    "datasheet": "Datasheets/RD3009600.pdf",
    "coating": "Nitrile",
    "style": [
      "Disposable",
      "Latex free",
      "Powder free",
      "Silicone free"
    ],
    "requirementsList": [
      "Foodsafe",
      "Touchscreen",
      "Waterproof"
    ],
    "industries": [
      "Agriculture",
      "Asbestos",
      "Assembly",
      "Automotive",
      "Chemical",
      "Construction",
      "Food Industry",
      "Insulation",
      "Janitorial",
      "Plumbing",
      "Touchscreens",
      "Veterinary"
    ]
  },
  {
    "code": "RD301040Q",
    "name": "Nitrylex Classic Black",
    "brand": "Mercator",
    "sizes": "S - XL",
    "image": "Images/RD301040Q.jpg",
    "datasheet": "Datasheets/RD301040Q.pdf",
    "style": [
      "Disposable",
      "Latex free",
      "Powder free",
      "Silicone free"
    ],
    "requirementsList": [
      "Foodsafe",
      "Touchscreen",
      "Waterproof"
    ],
    "industries": [
      "Asbestos",
      "Assembly",
      "Automotive",
      "Chemical",
      "Engineering",
      "Food Industry",
      "General Handling",
      "Insulation",
      "Janitorial",
      "Plumbing",
      "Touchscreens",
      "Veterinary"
    ]
  },
  {
    "code": "RD302370Q",
    "name": "Nitrylex Strong",
    "brand": "Mercator",
    "sizes": "S - 2XL",
    "image": "Images/RD302370Q.jpg",
    "datasheet": "Datasheets/RD302370Q.pdf",
    "coating": "Nitrile",
    "style": [
      "Disposable",
      "Latex free",
      "Powder free",
      "Silicone free"
    ],
    "requirementsList": [
      "Foodsafe",
      "Touchscreen",
      "Waterproof"
    ],
    "industries": [
      "Agriculture",
      "Asbestos",
      "Assembly",
      "Automotive",
      "Chemical",
      "Engineering",
      "Food Industry",
      "Insulation",
      "Janitorial",
      "Plumbing",
      "Touchscreens",
      "Veterinary"
    ]
  },
  {
    "code": "RP300260Q",
    "name": "Ideall Grip Black",
    "brand": "Mercator",
    "sizes": "S - 2XL",
    "image": "Images/RP300260Q.jpg",
    "datasheet": "Datasheets/RP300260Q.pdf",
    "coating": "Nitrile",
    "style": [
      "Diamond grip",
      "Disposable",
      "Latex free",
      "Powder free",
      "Silicone free"
    ],
    "requirementsList": [
      "Foodsafe",
      "Touchscreen",
      "Waterproof"
    ],
    "industries": [
      "Asbestos",
      "Assembly",
      "Automotive",
      "Chemical",
      "Engineering",
      "Food Industry",
      "Insulation",
      "Janitorial",
      "Plumbing",
      "Touchscreens",
      "Veterinary"
    ]
  },
  {
    "code": "RP300270Q",
    "name": "Ideall Grip Orange",
    "brand": "Mercator",
    "image": "Images/RP3002700.jpg",
    "datasheet": "Datasheets/RP3002700.pdf",
    "coating": "Nitrile",
    "style": [
      "Disposable",
      "Latex free",
      "Powder free",
      "Silicone free"
    ],
    "requirementsList": [
      "Foodsafe",
      "Touchscreen",
      "Waterproof"
    ],
    "industries": [
      "Asbestos",
      "Assembly",
      "Chemical",
      "Food Industry",
      "Insulation",
      "Janitorial",
      "Plumbing",
      "Touchscreens",
      "Veterinary"
    ]
  },
  {
    "code": "RP300326Q",
    "name": "Ideall Grip Green",
    "brand": "Mercator",
    "sizes": "S - 2XL",
    "image": "Images/RP300326Q.jpg",
    "datasheet": "Datasheets/RP300326Q.pdf",
    "style": [
      "Diamond grip",
      "Disposable",
      "Latex free",
      "Powder free",
      "Silicone free"
    ],
    "requirementsList": [
      "Foodsafe",
      "Touchscreen",
      "Waterproof"
    ],
    "industries": [
      "Agriculture",
      "Asbestos",
      "Assembly",
      "Automotive",
      "Chemical",
      "Construction",
      "Engineering",
      "Food Industry",
      "Insulation",
      "Janitorial",
      "Plumbing",
      "Touchscreens",
      "Veterinary"
    ]
  },
  {
    "code": "RP300376Q",
    "name": "Ideall Grip Blue (Long Cuff)",
    "brand": "Mercator",
    "sizes": "S - 2XL",
    "image": "Images/RP300376Q.jpg",
    "datasheet": "Datasheets/RP300376Q.pdf",
    "style": [
      "Diamond grip",
      "Disposable",
      "Latex free",
      "Powder free",
      "Silicone free"
    ],
    "requirementsList": [
      "Foodsafe",
      "Touchscreen",
      "Waterproof"
    ],
    "industries": [
      "Asbestos",
      "Assembly",
      "Automotive",
      "Chemical",
      "Engineering",
      "Food Industry",
      "General Handling",
      "Insulation",
      "Janitorial",
      "Plumbing",
      "Touchscreens",
      "Veterinary"
    ]
  },
  {
    "code": "RPET10DW",
    "name": "Spruce",
    "brand": "Planetsafe",
    "sizes": "7 - 11",
    "image": "Images/RPET10DW.jpg",
    "datasheet": "Datasheets/RPET10DW.pdf",
    "gauge": "10",
    "coating": "Foam Latex",
    "liner": "Acrylic Terry",
    "cutLevel": "Cut D",
    "requirementsList": [
      "Contact cold",
      "Contact Heat",
      "Cut protection",
      "Thermal"
    ],
    "industries": [
      "Cold stores",
      "Engineering",
      "Automotive",
      "Warehousing",
      "Scaffolding",
      "Rigging"
    ]
  },
  {
    "code": "RPET15A",
    "name": "Cedar",
    "brand": "Planetsafe",
    "sizes": "6 - 11",
    "image": "Images/RPET15A.jpg",
    "datasheet": "Datasheets/RPET15A.pdf",
    "gauge": "15",
    "coating": "Nitrile Foam",
    "liner": "Recycled Polyester",
    "cutLevel": "Cut 1",
    "requirementsList": [
      "Contact Heat"
    ],
    "industries": [
      "General Handling",
      "Warehousing",
      "Packaging",
      "Landscaping",
      "Construction",
      "Logistics"
    ]
  },
  {
    "code": "RPET15E",
    "name": "Maple",
    "brand": "Planetsafe",
    "sizes": "6 - 11",
    "image": "Images/RPET15E.jpg",
    "datasheet": "Datasheets/RPET15E.pdf",
    "gauge": "15",
    "coating": "Sandy Nitrile",
    "liner": "Recycled Polyester",
    "cutLevel": "Cut E",
    "requirementsList": [
      "Contact Heat",
      "Cut protection",
      "Touchscreen"
    ],
    "industries": [
      "Engineering",
      "Construction",
      "Assembly",
      "Agriculture",
      "Glass",
      "Glazing",
      "Fabrication"
    ]
  },
  {
    "code": "RS1B-VL",
    "name": "Power Plus XL",
    "brand": "Predator",
    "sizes": "11.5",
    "image": "Images/RS1B-VL.jpg",
    "datasheet": "Datasheets/RS1B-VL.pdf",
    "leather": "Split Leather",
    "liner": "100% Cotton",
    "cutLevel": "Cut 1",
    "industries": [
      "Agriculture",
      "Construction",
      "Foresty",
      "Rigging",
      "Scaffolding",
      "Warehousing"
    ]
  },
  {
    "code": "RS1C-TH",
    "name": "Winter Power",
    "brand": "Predator",
    "sizes": "10",
    "image": "Images/RS1C-TH.jpg",
    "datasheet": "Datasheets/RS1C-TH.pdf",
    "liner": "Thinsulate Liner",
    "cutLevel": "Cut 1",
    "requirementsList": [
      "Contact cold",
      "Contact Heat"
    ],
    "industries": [
      "Cold stores",
      "Construction",
      "Logistics",
      "Rigging",
      "Scaffolding",
      "Warehousing"
    ]
  },
  {
    "code": "RS2DP-B",
    "name": "Power Plus Double Palm",
    "brand": "Predator",
    "sizes": "10",
    "image": "Images/RS2DP-B.jpg",
    "datasheet": "Datasheets/RS2DP-B.pdf",
    "leather": "Split Leather",
    "liner": "100% Cotton",
    "cutLevel": "Cut 2",
    "requirementsList": [
      "Contact Heat"
    ],
    "industries": [
      "Construction",
      "General Handling",
      "Metal work",
      "Agriculture",
      "Foresty",
      "Scaffolding",
      "Warehousing"
    ]
  },
  {
    "code": "RSW1C",
    "name": "Lightning Red Mig",
    "brand": "Predator",
    "sizes": "11",
    "image": "Images/RSW1C.jpg",
    "datasheet": "Datasheets/RSW1C.pdf",
    "leather": "Split Leather",
    "liner": "100% Cotton",
    "cutLevel": "Cut 1",
    "requirementsList": [
      "Contact Heat"
    ],
    "industries": [
      "Arc Welding",
      "Construction",
      "Engineering",
      "Fabrication",
      "Metal work",
      "Mig Welding",
      "Welding",
      "Work gloves"
    ]
  },
  {
    "code": "RSW1C-BLUE",
    "name": "Lightning Blue Mig",
    "brand": "Predator",
    "sizes": "11",
    "image": "Images/RSW1C-BLUE.jpg",
    "datasheet": "Datasheets/RSW1C-BLUE.pdf",
    "leather": "Split Leather",
    "liner": "100% Cotton",
    "cutLevel": "Cut 1",
    "requirementsList": [
      "Contact Heat"
    ],
    "industries": [
      "Arc Welding",
      "Construction",
      "Engineering",
      "Fabrication",
      "Forging",
      "Mig Welding"
    ]
  },
  {
    "code": "RSW1C-BLUE-S",
    "name": "Lightning Blue Small",
    "brand": "Planetsafe",
    "sizes": "9",
    "image": "Images/RSW1C-BLUE-S.jpg",
    "datasheet": "Datasheets/RSW1C-BLUE-S.pdf",
    "leather": "Split Leather",
    "liner": "100% Cotton",
    "cutLevel": "Cut 1",
    "requirementsList": [
      "Contact Heat"
    ],
    "industries": [
      "Arc Welding",
      "Construction",
      "Engineering",
      "Fabrication",
      "Forging",
      "Mig Welding"
    ]
  },
  {
    "code": "RSW1C-KEV",
    "name": "Lightning Twaron Mig",
    "brand": "Predator",
    "sizes": "11",
    "image": "Images/RSW1C-KEV.jpg",
    "datasheet": "Datasheets/RSW1C-KEV.pdf",
    "leather": "Split Leather",
    "liner": "100% Cotton",
    "cutLevel": "Cut 1",
    "requirementsList": [
      "Contact Heat"
    ],
    "industries": [
      "Arc Welding",
      "Construction",
      "Engineering",
      "Fabrication",
      "Metal work",
      "Mig Welding"
    ]
  },
  {
    "code": "RSW1C-REV",
    "name": "Lightning Reversible",
    "brand": "Predator",
    "sizes": "11",
    "image": "Images/RSW1C-REV.jpg",
    "datasheet": "Datasheets/RSW1C-REV.pdf",
    "leather": "Split Leather",
    "liner": "100% Cotton",
    "cutLevel": "Cut 1",
    "requirementsList": [
      "Contact Heat"
    ],
    "industries": [
      "Arc Welding",
      "Construction",
      "Engineering",
      "Fabrication",
      "Metal work",
      "Mig Welding"
    ]
  },
  {
    "code": "SL1HRF",
    "name": "Cobra Sleeve",
    "brand": "Miscellaneous",
    "sizes": "45CM",
    "image": "Images/SL1HRF.jpg",
    "datasheet": "Datasheets/SL1HRF.pdf",
    "gauge": "13",
    "cutLevel": "Cut F",
    "style": [
      "Sleeves"
    ],
    "requirementsList": [
      "Contact Heat"
    ],
    "industries": [
      "Agriculture",
      "Automotive",
      "Engineering",
      "Sheet work",
      "Welding"
    ]
  },
  {
    "code": "SL2CLD",
    "name": "Python Sleeve",
    "brand": "Miscellaneous",
    "sizes": "45CM",
    "image": "Images/SL2CLD.jpg",
    "datasheet": "Datasheets/SL2CLD.pdf",
    "gauge": "18",
    "cutLevel": "Cut D",
    "style": [
      "Sleeves"
    ],
    "industries": [
      "Agriculture",
      "Automotive",
      "Engineering",
      "Sheet work",
      "Welding"
    ]
  },
  {
    "code": "SL3VIPD",
    "name": "Viper Sleeve",
    "brand": "Miscellaneous",
    "sizes": "45CM",
    "image": "Images/SL3VIPD.jpg",
    "datasheet": "Datasheets/SL3VIPD.pdf",
    "gauge": "13",
    "cutLevel": "Cut D",
    "style": [
      "Sleeves"
    ],
    "industries": [
      "Agriculture",
      "Automotive",
      "Engineering",
      "Sheet work",
      "Welding"
    ]
  },
  {
    "code": "SN13DTQ",
    "name": "Sigma",
    "brand": "Touchsafe",
    "sizes": "6 - 11",
    "image": "Images/SN13DTQ.jpg",
    "datasheet": "Datasheets/SN13DTQ.pdf",
    "gauge": "13",
    "coating": "Sandy Nitrile",
    "liner": "Spandex liner",
    "cutLevel": "Cut D",
    "requirementsList": [
      "Contact Heat",
      "Cut protection",
      "Touchscreen",
      "Vend Ready"
    ],
    "industries": [
      "Agriculture",
      "Construction",
      "Food Industry",
      "Glass",
      "Glazing",
      "Landscaping",
      "Metal work",
      "Packaging",
      "Scaffolding",
      "Touchscreens",
      "Warehousing"
    ]
  },
  {
    "code": "TS1",
    "name": "Sensor",
    "brand": "Touchsafe",
    "sizes": "6 - 11",
    "image": "Images/TS1.jpg",
    "datasheet": "Datasheets/TS1.pdf",
    "gauge": "15",
    "coating": "Polymax",
    "liner": "Nylon Liner",
    "cutLevel": "Cut 1",
    "requirementsList": [
      "Foodsafe",
      "Touchscreen"
    ],
    "industries": [
      "Assembly",
      "Automotive",
      "Engineering",
      "Food Industry",
      "Touchscreens"
    ]
  },
  {
    "code": "TS4",
    "name": "Impact",
    "brand": "Touchsafe",
    "sizes": "8 - 11",
    "image": "Images/TS4.jpg",
    "datasheet": "Datasheets/TS4.pdf",
    "gauge": "18",
    "coating": "Polymax",
    "liner": "Nylon Liner",
    "cutLevel": "Cut F",
    "requirementsList": [
      "Contact Heat",
      "Cut protection",
      "Foodsafe",
      "Impact",
      "Touchscreen"
    ],
    "industries": [
      "Automotive",
      "Fabrication",
      "Food Industry",
      "Glass",
      "Glazing",
      "Metal work",
      "Touchscreens"
    ]
  },
  {
    "code": "WPTL7CL",
    "name": "Alaska",
    "brand": "Coloursafe",
    "sizes": "7 - 11",
    "image": "Images/WPTL7CL.jpg",
    "datasheet": "Datasheets/WPTL7CL.pdf",
    "gauge": "7",
    "coating": "Crinkle Latex",
    "liner": "Polyester Liner",
    "cutLevel": "Cut 1",
    "requirementsList": [
      "Contact cold",
      "Thermal"
    ],
    "industries": [
      "Cold stores",
      "Scaffolding",
      "Agriculture",
      "Banksmen",
      "Construction",
      "Engineering"
    ]
  },
  {
    "code": "WS1",
    "name": "Atlantic",
    "brand": "Watersafe",
    "sizes": "7 - 11",
    "image": "Images/WS1.jpg",
    "datasheet": "Datasheets/WS1.pdf",
    "gauge": "15",
    "coating": "Latex",
    "liner": "Nylon Liner",
    "cutLevel": "Cut 1",
    "requirementsList": [
      "Contact Heat",
      "Waterproof"
    ],
    "industries": [
      "Banksmen",
      "Construction",
      "Engineering",
      "General Handling",
      "Landscaping",
      "Scaffolding",
      "Work gloves"
    ]
  },
  {
    "code": "WS4",
    "name": "Baltic",
    "brand": "Watersafe",
    "sizes": "7 - 11",
    "image": "Images/WS4.jpg",
    "datasheet": "Datasheets/WS4.pdf",
    "gauge": "15",
    "coating": "Latex",
    "liner": "Acrylic liner",
    "cutLevel": "Cut 2",
    "requirementsList": [
      "Contact Heat",
      "Waterproof"
    ],
    "industries": [
      "Cold stores",
      "Construction",
      "Engineering",
      "Landscaping",
      "Logistics",
      "Scaffolding",
      "Work gloves"
    ]
  },
  {
    "code": "WS5",
    "name": "Arctic",
    "brand": "Watersafe",
    "sizes": "8 - 11",
    "image": "Images/WS5.jpg",
    "datasheet": "Datasheets/WS5.pdf",
    "gauge": "13",
    "coating": "Sandy Nitrile",
    "liner": "Acrylic liner",
    "cutLevel": "Cut E",
    "requirementsList": [
      "Contact cold",
      "Contact Heat",
      "Thermal",
      "Waterproof"
    ],
    "industries": [
      "Cold stores",
      "Construction",
      "Engineering",
      "Metal work",
      "Recycling",
      "Waste Management"
    ]
  },
  {
    "code": "WS6",
    "name": "Congo",
    "brand": "Watersafe",
    "sizes": "6 - 11",
    "image": "Images/WS6.jpg",
    "datasheet": "Datasheets/WS6.pdf",
    "gauge": "13",
    "coating": "Latex",
    "liner": "Polyester Liner",
    "cutLevel": "Cut 1",
    "requirementsList": [
      "Waterproof"
    ],
    "industries": [
      "Banksmen",
      "Construction",
      "Engineering",
      "General Handling",
      "Landscaping",
      "Scaffolding"
    ]
  },
  {
    "code": "WS7",
    "name": "Yukon",
    "brand": "Watersafe",
    "sizes": "7 - 11",
    "image": "Images/WS7.jpg",
    "datasheet": "Datasheets/WS7.pdf",
    "gauge": "15",
    "coating": "Latex",
    "liner": "Polyester Liner",
    "cutLevel": "Cut E",
    "requirementsList": [
      "Contact cold",
      "Cut protection",
      "Thermal",
      "Waterproof"
    ],
    "industries": [
      "Cold stores",
      "Glass",
      "Recycling",
      "Waste Management",
      "Construction",
      "Engineering",
      "General Handling"
    ]
  },
  {
    "code": "WS8",
    "name": "Persian",
    "brand": "Watersafe",
    "sizes": "6 - 11",
    "image": "Images/WS8.jpg",
    "datasheet": "Datasheets/WS8.pdf",
    "gauge": "15",
    "coating": "Nitrile",
    "liner": "Nylon Liner",
    "cutLevel": "Cut 1",
    "requirementsList": [
      "Contact Heat",
      "Waterproof"
    ],
    "industries": [
      "Cold stores",
      "Construction",
      "Engineering",
      "General Handling",
      "Landscaping",
      "Scaffolding"
    ]
  },
  {
    "code": "WS9",
    "name": "Caspian",
    "brand": "Watersafe",
    "sizes": "7 - 11",
    "image": "Images/WS9.jpg",
    "datasheet": "Datasheets/WS9.pdf",
    "gauge": "13",
    "coating": "Nitrile",
    "liner": "Nylon Liner",
    "cutLevel": "Cut F",
    "requirementsList": [
      "Contact Heat",
      "Cut protection",
      "Waterproof"
    ],
    "industries": [
      "Banksmen",
      "Engineering",
      "Glass",
      "Recycling",
      "Work gloves"
    ]
  }
];

window.FILTERS = 
{
  "categories": {
    "Brand": [
      "Coloursafe",
      "Mercator",
      "Mig Gauntlets",
      "Miscellaneous",
      "Planetsafe",
      "Predator",
      "Rigger Gloves",
      "Specialist",
      "Touchsafe",
      "Watersafe"
    ],
    "Coating": [
      "Crinkle Latex",
      "Foam Latex",
      "Latex",
      "Leather",
      "Nitrile",
      "Nitrile Foam",
      "Nitrile Micro Foam",
      "PU",
      "PVC",
      "Polymax",
      "Polymer",
      "Sandy Nitrile",
      "Smooth Nitrile"
    ],
    "Cut Level": [
      "Cut 1",
      "Cut 2",
      "Cut C",
      "Cut D",
      "Cut E",
      "Cut F",
      "Cut level A",
      "Cut level B"
    ],
    "Gauge": [
      "10",
      "13",
      "15",
      "18",
      "7",
      "8oz Cotton Drill"
    ],
    "Industry": [
      "Agriculture",
      "Arc Welding",
      "Asbestos",
      "Assembly",
      "Automotive",
      "Banksmen",
      "Chemical",
      "Cold stores",
      "Concrete Breakers",
      "Construction",
      "Engineering",
      "Fabrication",
      "Fine Arts",
      "Food Industry",
      "Foresty",
      "Forging",
      "Gardening",
      "General Handling",
      "Glass",
      "Glazing",
      "Inspection",
      "Insulation",
      "Janitorial",
      "Landscaping",
      "Logistics",
      "Metal work",
      "Mig Welding",
      "Mining",
      "Needle Stick",
      "Packaging",
      "Plumbing",
      "Recycling",
      "Refuse",
      "Rigging",
      "Scaffolding",
      "Sheet work",
      "Tig Welding",
      "Touchscreens",
      "Veterinary",
      "Warehousing",
      "Waste Management",
      "Welding",
      "Work gloves"
    ],
    "Leather": [
      "Deer Hide",
      "Goat Skin",
      "Hide Leather",
      "Rigger",
      "Split Leather"
    ],
    "Liner Material": [
      "100% Cotton",
      "Acrylic Terry",
      "Acrylic liner",
      "Azura Liner",
      "Flock Lined",
      "Jersey Liner",
      "Metal Q",
      "Natural Cotton Liner",
      "Nylon Liner",
      "Polycotton Liner",
      "Polyester Liner",
      "Polyethylene",
      "Recycled Polyester",
      "Spandex liner",
      "Steel liner",
      "Tekarmor",
      "Thinsulate Liner",
      "UHMWPE"
    ],
    "Requirements": [
      "Anti Vibration",
      "Contact Heat",
      "Contact cold",
      "Cut protection",
      "Foodsafe",
      "Impact",
      "Minimal Risk",
      "Needle Resistant",
      "Thermal",
      "Touchscreen",
      "Vend Ready",
      "Vibration",
      "Waterproof"
    ],
    "Style": [
      "Diamond grip",
      "Disposable",
      "Latex free",
      "Powder free",
      "Silicone free",
      "Sleeves"
    ]
  },
  "productMap": {
    "2LCTC": {
      "Brand": [
        "Coloursafe"
      ],
      "Coating": [
        "Crinkle Latex"
      ],
      "Cut Level": [
        "Cut 1"
      ],
      "Gauge": [
        "13"
      ],
      "Industry": [
        "Agriculture",
        "Construction",
        "Engineering",
        "Landscaping",
        "Scaffolding"
      ],
      "Liner Material": [
        "Polycotton Liner"
      ]
    },
    "BLACKPUPL": {
      "Brand": [
        "Coloursafe"
      ],
      "Coating": [
        "PU"
      ],
      "Cut Level": [
        "Cut 1"
      ],
      "Gauge": [
        "13"
      ],
      "Industry": [
        "Agriculture",
        "Banksmen",
        "Construction",
        "General Handling",
        "Scaffolding",
        "Warehousing"
      ],
      "Liner Material": [
        "Polyester Liner"
      ],
      "Requirements": [
        "Vend Ready"
      ]
    },
    "CCMPP": {
      "Brand": [
        "Coloursafe"
      ],
      "Coating": [
        "Leather"
      ],
      "Cut Level": [
        "Cut 1"
      ],
      "Gauge": [
        "8oz Cotton Drill"
      ],
      "Industry": [
        "Assembly",
        "Construction",
        "Gardening",
        "General Handling",
        "Packaging",
        "Warehousing"
      ],
      "Liner Material": [
        "100% Cotton"
      ]
    },
    "EZ324VR": {
      "Requirements": [
        "Foodsafe",
        "Touchscreen",
        "Vend Ready"
      ],
      "Industry": [
        "Arc Welding",
        "Asbestos"
      ],
      "Coating": [
        "Polymer"
      ],
      "Cut Level": [
        "Cut 1"
      ],
      "Liner Material": [
        "Nylon Liner",
        "Spandex liner"
      ],
      "Style": [
        "Diamond grip",
        "Disposable"
      ],
      "Gauge": [
        "18"
      ]
    },
    "HAR2": {
      "Cut Level": [
        "Cut 2"
      ],
      "Leather": [
        "Split Leather"
      ],
      "Industry": [
        "Agriculture",
        "Construction",
        "Foresty",
        "General Handling",
        "Metal work",
        "Scaffolding",
        "Warehousing"
      ],
      "Liner Material": [
        "100% Cotton"
      ]
    },
    "HAWG2": {
      "Cut Level": [
        "Cut 2"
      ],
      "Requirements": [
        "Contact Heat"
      ],
      "Leather": [
        "Split Leather"
      ],
      "Industry": [
        "Arc Welding",
        "Engineering",
        "Metal work",
        "Mig Welding",
        "Construction",
        "Fabrication"
      ],
      "Liner Material": [
        "100% Cotton"
      ]
    },
    "LCPLRED": {
      "Gauge": [
        "13"
      ],
      "Coating": [
        "Crinkle Latex"
      ],
      "Cut Level": [
        "Cut 1"
      ],
      "Liner Material": [
        "Polyester Liner"
      ],
      "Style": [
        "Latex free"
      ],
      "Industry": [
        "Construction",
        "Engineering",
        "General Handling"
      ]
    },
    "LCTCTD": {
      "Brand": [
        "Coloursafe"
      ],
      "Coating": [
        "Latex"
      ],
      "Cut Level": [
        "Cut level B",
        "Cut 1"
      ],
      "Liner Material": [
        "Polycotton Liner"
      ],
      "Industry": [
        "Agriculture",
        "Banksmen",
        "Construction",
        "Engineering",
        "Scaffolding"
      ]
    },
    "MF15A": {
      "Cut Level": [
        "Cut level A"
      ],
      "Requirements": [
        "Contact Heat",
        "Touchscreen"
      ],
      "Liner Material": [
        "Nylon Liner",
        "Spandex liner"
      ],
      "Industry": [
        "Construction",
        "Food Industry",
        "General Handling",
        "Landscaping",
        "Packaging",
        "Scaffolding",
        "Touchscreens",
        "Warehousing"
      ],
      "Gauge": [
        "15"
      ],
      "Coating": [
        "Nitrile Micro Foam"
      ]
    },
    "NFPLR": {
      "Gauge": [
        "13"
      ],
      "Coating": [
        "Nitrile Foam"
      ],
      "Cut Level": [
        "Cut 1"
      ],
      "Liner Material": [
        "Polyester Liner"
      ],
      "Requirements": [
        "Contact Heat"
      ],
      "Industry": [
        "Agriculture",
        "Banksmen",
        "Construction",
        "General Handling",
        "Landscaping"
      ]
    },
    "NITGFL330": {
      "Cut Level": [
        "Cut 1"
      ],
      "Requirements": [
        "Foodsafe",
        "Touchscreen"
      ],
      "Industry": [
        "Chemical",
        "Food Industry",
        "Janitorial",
        "Touchscreens"
      ],
      "Brand": [
        "Mercator"
      ],
      "Coating": [
        "Nitrile"
      ],
      "Liner Material": [
        "Flock Lined"
      ]
    },
    "NITKW": {
      "Cut Level": [
        "Cut 1"
      ],
      "Coating": [
        "Nitrile"
      ],
      "Requirements": [
        "Waterproof"
      ],
      "Industry": [
        "Banksmen",
        "Construction",
        "General Handling",
        "Packaging",
        "Scaffolding",
        "Warehousing"
      ],
      "Liner Material": [
        "Jersey Liner"
      ]
    },
    "NITSC": {
      "Cut Level": [
        "Cut 1"
      ],
      "Coating": [
        "Nitrile"
      ],
      "Liner Material": [
        "Jersey Liner"
      ],
      "Industry": [
        "Banksmen",
        "Construction",
        "General Handling",
        "Packaging",
        "Scaffolding",
        "Warehousing"
      ]
    },
    "NSPL": {
      "Coating": [
        "Smooth Nitrile"
      ],
      "Cut Level": [
        "Cut 1",
        "Cut level A"
      ],
      "Liner Material": [
        "Polyester Liner"
      ],
      "Industry": [
        "Banksmen",
        "Construction",
        "Engineering",
        "General Handling",
        "Landscaping",
        "Scaffolding",
        "Warehousing",
        "Agriculture"
      ],
      "Gauge": [
        "13"
      ]
    },
    "PRED1": {
      "Cut Level": [
        "Cut 2"
      ],
      "Leather": [
        "Split Leather"
      ],
      "Industry": [
        "Agriculture",
        "Construction",
        "Foresty",
        "General Handling",
        "Metal work",
        "Scaffolding",
        "Warehousing"
      ],
      "Liner Material": [
        "100% Cotton"
      ],
      "Brand": [
        "Predator"
      ]
    },
    "PRED1HV": {
      "Cut Level": [
        "Cut 2"
      ],
      "Liner Material": [
        "100% Cotton"
      ],
      "Industry": [
        "Agriculture",
        "Construction",
        "Foresty",
        "Rigging",
        "Scaffolding"
      ],
      "Leather": [
        "Split Leather"
      ],
      "Brand": [
        "Predator"
      ]
    },
    "PRED12": {
      "Coating": [
        "Foam Latex"
      ],
      "Cut Level": [
        "Cut F"
      ],
      "Requirements": [
        "Cut protection",
        "Needle",
        "Needle Resistant",
        "Waterproof"
      ],
      "Industry": [
        "Glass",
        "Glazing",
        "Metal work",
        "Needle Stick",
        "Recycling"
      ],
      "Gauge": [
        "10"
      ]
    },
    "PRED13": {
      "Coating": [
        "PU"
      ],
      "Cut Level": [
        "Cut F"
      ],
      "Requirements": [
        "Cut protection",
        "Vend Ready"
      ],
      "Liner Material": [
        "Polyester Liner",
        "Spandex liner",
        "Steel liner"
      ],
      "Industry": [
        "Agriculture",
        "Assembly",
        "Automotive",
        "Construction",
        "Engineering",
        "Fabrication",
        "Glass",
        "Sheet work"
      ],
      "Gauge": [
        "13"
      ]
    },
    "PRED16": {
      "Cut Level": [
        "Cut 1"
      ],
      "Industry": [
        "Concrete Breakers",
        "Construction",
        "Engineering",
        "Mining"
      ],
      "Requirements": [
        "Anti Vibration"
      ],
      "Leather": [
        "Goat Skin"
      ]
    },
    "PRED2": {
      "Cut Level": [
        "Cut 1"
      ],
      "Leather": [
        "Hide Leather",
        "Rigger"
      ],
      "Industry": [
        "Agriculture",
        "Construction",
        "Foresty",
        "General Handling",
        "Metal work",
        "Scaffolding",
        "Warehousing",
        "Work gloves"
      ],
      "Liner Material": [
        "100% Cotton"
      ],
      "Brand": [
        "Predator"
      ]
    },
    "PRED2GOLD": {
      "Leather": [
        "Hide Leather",
        "Rigger"
      ],
      "Industry": [
        "Agriculture",
        "Construction",
        "Foresty",
        "General Handling",
        "Metal work",
        "Scaffolding",
        "Warehousing",
        "Work gloves"
      ],
      "Cut Level": [
        "Cut 1"
      ],
      "Liner Material": [
        "100% Cotton"
      ],
      "Brand": [
        "Predator"
      ]
    },
    "PRED315": {
      "Cut Level": [
        "Cut 1"
      ],
      "Liner Material": [
        "100% Cotton"
      ],
      "Leather": [
        "Hide Leather"
      ],
      "Industry": [
        "Agriculture",
        "Construction",
        "Foresty",
        "General Handling",
        "Logistics",
        "Scaffolding",
        "Warehousing"
      ],
      "Brand": [
        "Predator"
      ]
    },
    "PRED3GOLD": {
      "Cut Level": [
        "Cut 1"
      ],
      "Leather": [
        "Hide Leather"
      ],
      "Industry": [
        "Agriculture",
        "Construction",
        "General Handling",
        "Logistics",
        "Rigging",
        "Warehousing",
        "Foresty",
        "Scaffolding"
      ],
      "Liner Material": [
        "100% Cotton"
      ],
      "Brand": [
        "Predator"
      ]
    },
    "PRED3SB": {
      "Cut Level": [
        "Cut 1"
      ],
      "Liner Material": [
        "100% Cotton"
      ],
      "Leather": [
        "Hide Leather"
      ],
      "Industry": [
        "Agriculture",
        "Construction",
        "General Handling",
        "Rigging",
        "Scaffolding",
        "Warehousing"
      ],
      "Brand": [
        "Predator"
      ]
    },
    "PRED4": {
      "Cut Level": [
        "Cut 2"
      ],
      "Requirements": [
        "Contact Heat"
      ],
      "Leather": [
        "Split Leather"
      ],
      "Industry": [
        "Arc Welding",
        "Construction",
        "Engineering",
        "Fabrication",
        "Metal work",
        "Mig Welding",
        "Welding"
      ],
      "Liner Material": [
        "100% Cotton"
      ],
      "Brand": [
        "Predator"
      ]
    },
    "PRED416": {
      "Cut Level": [
        "Cut 2"
      ],
      "Liner Material": [
        "100% Cotton"
      ],
      "Requirements": [
        "Contact Heat"
      ],
      "Leather": [
        "Split Leather"
      ],
      "Industry": [
        "Arc Welding",
        "Construction",
        "Fabrication",
        "Forging",
        "Metal work",
        "Mig Welding"
      ]
    },
    "PRED4GLOVE": {
      "Liner Material": [
        "100% Cotton"
      ],
      "Brand": [
        "Predator"
      ],
      "Cut Level": [
        "Cut 1"
      ],
      "Requirements": [
        "Contact Heat"
      ],
      "Leather": [
        "Split Leather"
      ],
      "Industry": [
        "Construction",
        "Engineering",
        "Forging",
        "Fabrication",
        "Metal work"
      ]
    },
    "PRED4THORN": {
      "Cut Level": [
        "Cut 2"
      ],
      "Liner Material": [
        "100% Cotton"
      ],
      "Requirements": [
        "Contact Heat",
        "Needle Resistant"
      ],
      "Leather": [
        "Split Leather"
      ],
      "Industry": [
        "Gardening",
        "Foresty",
        "Landscaping"
      ]
    },
    "PRED6": {
      "Cut Level": [
        "Cut 1"
      ],
      "Requirements": [
        "Contact Heat"
      ],
      "Leather": [
        "Hide Leather"
      ],
      "Industry": [
        "Agriculture",
        "Construction",
        "Engineering",
        "Forging",
        "Metal work",
        "Tig Welding",
        "Welding"
      ],
      "Brand": [
        "Predator"
      ],
      "Liner Material": [
        "100% Cotton"
      ]
    },
    "PRED6C": {
      "Brand": [
        "Predator"
      ],
      "Cut Level": [
        "Cut 1"
      ],
      "Liner Material": [
        "100% Cotton"
      ],
      "Requirements": [
        "Contact Heat"
      ],
      "Leather": [
        "Hide Leather"
      ],
      "Industry": [
        "Agriculture",
        "Construction",
        "Engineering",
        "Forging",
        "Metal work",
        "Tig Welding"
      ]
    },
    "PRED6D": {
      "Cut Level": [
        "Cut 1"
      ],
      "Requirements": [
        "Contact Heat"
      ],
      "Leather": [
        "Deer Hide"
      ],
      "Industry": [
        "Agriculture",
        "Construction",
        "Engineering",
        "Forging",
        "Tig Welding",
        "Metal work"
      ],
      "Brand": [
        "Predator"
      ],
      "Liner Material": [
        "100% Cotton"
      ]
    },
    "PRED6GLOVE": {
      "Brand": [
        "Predator"
      ],
      "Cut Level": [
        "Cut 1"
      ],
      "Liner Material": [
        "100% Cotton"
      ],
      "Requirements": [
        "Contact Heat"
      ],
      "Leather": [
        "Hide Leather"
      ],
      "Industry": [
        "Agriculture",
        "Construction",
        "Engineering",
        "Forging",
        "Metal work",
        "Tig Welding"
      ]
    },
    "PRKW10": {
      "Coating": [
        "PVC"
      ],
      "Cut Level": [
        "Cut 1"
      ],
      "Liner Material": [
        "Natural Cotton Liner"
      ],
      "Industry": [
        "Assembly",
        "Construction",
        "Gardening",
        "General Handling",
        "Packaging",
        "Warehousing"
      ]
    },
    "PU13D": {
      "Coating": [
        "PU"
      ],
      "Cut Level": [
        "Cut D"
      ],
      "Requirements": [
        "Cut protection"
      ],
      "Liner Material": [
        "Polyester Liner",
        "Spandex liner",
        "UHMWPE"
      ],
      "Industry": [
        "Agriculture",
        "Construction",
        "Engineering",
        "General Handling",
        "Glass",
        "Landscaping",
        "Packaging",
        "Scaffolding",
        "Warehousing"
      ],
      "Gauge": [
        "13"
      ]
    },
    "PUPL": {
      "Coating": [
        "PU"
      ],
      "Cut Level": [
        "Cut 1",
        "Cut level A"
      ],
      "Liner Material": [
        "Polyester Liner"
      ],
      "Industry": [
        "Automotive",
        "Banksmen",
        "Construction",
        "Engineering",
        "General Handling",
        "Landscaping",
        "Scaffolding",
        "Warehousing"
      ],
      "Gauge": [
        "13"
      ]
    },
    "PUUH13": {
      "Gauge": [
        "13"
      ],
      "Coating": [
        "PU"
      ],
      "Cut Level": [
        "Cut C"
      ],
      "Liner Material": [
        "Azura Liner",
        "Polyester Liner"
      ],
      "Requirements": [
        "Cut protection"
      ],
      "Industry": [
        "Construction",
        "Engineering",
        "General Handling",
        "Landscaping",
        "Scaffolding"
      ]
    },
    "RD300199Q": {
      "Requirements": [
        "Foodsafe",
        "Touchscreen"
      ],
      "Industry": [
        "Food Industry",
        "Touchscreens"
      ],
      "Style": [
        "Diamond grip",
        "Disposable",
        "Latex free",
        "Powder free",
        "Silicone free"
      ],
      "Brand": [
        "Mercator"
      ],
      "Coating": [
        "Nitrile"
      ]
    },
    "RD3009600": {
      "Coating": [
        "Nitrile"
      ],
      "Requirements": [
        "Foodsafe",
        "Touchscreen",
        "Waterproof"
      ],
      "Industry": [
        "Agriculture",
        "Asbestos",
        "Assembly",
        "Automotive",
        "Chemical",
        "Construction",
        "Food Industry",
        "Insulation",
        "Janitorial",
        "Plumbing",
        "Touchscreens",
        "Veterinary"
      ],
      "Style": [
        "Disposable",
        "Latex free",
        "Powder free",
        "Silicone free"
      ],
      "Brand": [
        "Mercator"
      ]
    },
    "RD301040Q": {
      "Requirements": [
        "Foodsafe",
        "Touchscreen",
        "Waterproof"
      ],
      "Industry": [
        "Asbestos",
        "Assembly",
        "Automotive",
        "Chemical",
        "Engineering",
        "Food Industry",
        "General Handling",
        "Insulation",
        "Janitorial",
        "Plumbing",
        "Touchscreens",
        "Veterinary"
      ],
      "Style": [
        "Disposable",
        "Latex free",
        "Powder free",
        "Silicone free"
      ],
      "Brand": [
        "Mercator"
      ]
    },
    "RD302370Q": {
      "Coating": [
        "Nitrile"
      ],
      "Requirements": [
        "Foodsafe",
        "Touchscreen",
        "Waterproof"
      ],
      "Industry": [
        "Agriculture",
        "Asbestos",
        "Assembly",
        "Automotive",
        "Chemical",
        "Engineering",
        "Food Industry",
        "Insulation",
        "Janitorial",
        "Plumbing",
        "Touchscreens",
        "Veterinary"
      ],
      "Style": [
        "Disposable",
        "Latex free",
        "Powder free",
        "Silicone free"
      ],
      "Brand": [
        "Mercator"
      ]
    },
    "RP300260Q": {
      "Coating": [
        "Nitrile"
      ],
      "Requirements": [
        "Foodsafe",
        "Touchscreen",
        "Waterproof"
      ],
      "Industry": [
        "Asbestos",
        "Assembly",
        "Automotive",
        "Chemical",
        "Engineering",
        "Food Industry",
        "Insulation",
        "Janitorial",
        "Plumbing",
        "Touchscreens",
        "Veterinary"
      ],
      "Style": [
        "Diamond grip",
        "Disposable",
        "Latex free",
        "Powder free",
        "Silicone free"
      ],
      "Brand": [
        "Mercator"
      ]
    },
    "RP300270Q": {
      "Industry": [
        "Asbestos",
        "Assembly",
        "Chemical",
        "Food Industry",
        "Insulation",
        "Janitorial",
        "Plumbing",
        "Touchscreens",
        "Veterinary"
      ],
      "Style": [
        "Disposable",
        "Latex free",
        "Powder free",
        "Silicone free"
      ],
      "Brand": [
        "Mercator"
      ],
      "Requirements": [
        "Foodsafe",
        "Touchscreen",
        "Waterproof"
      ],
      "Coating": [
        "Nitrile"
      ]
    },
    "RP300326Q": {
      "Requirements": [
        "Foodsafe",
        "Touchscreen",
        "Waterproof"
      ],
      "Industry": [
        "Agriculture",
        "Asbestos",
        "Assembly",
        "Automotive",
        "Chemical",
        "Construction",
        "Engineering",
        "Food Industry",
        "Insulation",
        "Janitorial",
        "Plumbing",
        "Touchscreens",
        "Veterinary"
      ],
      "Style": [
        "Diamond grip",
        "Disposable",
        "Latex free",
        "Powder free",
        "Silicone free"
      ],
      "Brand": [
        "Mercator"
      ]
    },
    "RP300376Q": {
      "Requirements": [
        "Foodsafe",
        "Touchscreen",
        "Waterproof"
      ],
      "Industry": [
        "Asbestos",
        "Assembly",
        "Automotive",
        "Chemical",
        "Engineering",
        "Food Industry",
        "General Handling",
        "Insulation",
        "Janitorial",
        "Plumbing",
        "Touchscreens",
        "Veterinary"
      ],
      "Style": [
        "Diamond grip",
        "Disposable",
        "Latex free",
        "Powder free",
        "Silicone free"
      ],
      "Brand": [
        "Mercator"
      ]
    },
    "RPET10DW": {
      "Requirements": [
        "Contact cold",
        "Contact Heat",
        "Cut protection",
        "Thermal"
      ],
      "Industry": [
        "Cold stores",
        "Engineering",
        "Automotive",
        "Warehousing",
        "Scaffolding",
        "Rigging"
      ],
      "Gauge": [
        "10"
      ],
      "Coating": [
        "Foam Latex"
      ],
      "Cut Level": [
        "Cut D"
      ],
      "Liner Material": [
        "Acrylic Terry",
        "Recycled Polyester",
        "Metal Q"
      ]
    },
    "RPET15A": {
      "Cut Level": [
        "Cut 1"
      ],
      "Liner Material": [
        "Recycled Polyester"
      ],
      "Gauge": [
        "15"
      ],
      "Coating": [
        "Nitrile Foam"
      ],
      "Requirements": [
        "Contact Heat"
      ],
      "Industry": [
        "General Handling",
        "Warehousing",
        "Packaging",
        "Landscaping",
        "Construction",
        "Logistics"
      ]
    },
    "RPET15E": {
      "Cut Level": [
        "Cut E"
      ],
      "Requirements": [
        "Contact Heat",
        "Cut protection",
        "Touchscreen"
      ],
      "Liner Material": [
        "Recycled Polyester",
        "Metal Q",
        "Spandex liner"
      ],
      "Gauge": [
        "15"
      ],
      "Coating": [
        "Sandy Nitrile"
      ],
      "Industry": [
        "Engineering",
        "Construction",
        "Assembly",
        "Agriculture",
        "Glass",
        "Glazing",
        "Fabrication"
      ]
    },
    "RS1BVL": {
      "Brand": [
        "Predator"
      ],
      "Cut Level": [
        "Cut 1"
      ],
      "Liner Material": [
        "100% Cotton"
      ],
      "Leather": [
        "Split Leather"
      ],
      "Industry": [
        "Agriculture",
        "Construction",
        "Foresty",
        "Rigging",
        "Scaffolding",
        "Warehousing"
      ]
    },
    "RS1CTH": {
      "Brand": [
        "Predator"
      ],
      "Cut Level": [
        "Cut 1"
      ],
      "Liner Material": [
        "Thinsulate Liner"
      ],
      "Requirements": [
        "Contact cold",
        "Contact Heat"
      ],
      "Industry": [
        "Cold stores",
        "Construction",
        "Logistics",
        "Rigging",
        "Scaffolding",
        "Warehousing"
      ]
    },
    "RS2DPB": {
      "Industry": [
        "Construction",
        "General Handling",
        "Metal work",
        "Agriculture",
        "Foresty",
        "Scaffolding",
        "Warehousing"
      ],
      "Brand": [
        "Predator"
      ],
      "Cut Level": [
        "Cut 2"
      ],
      "Liner Material": [
        "100% Cotton"
      ],
      "Requirements": [
        "Contact Heat"
      ],
      "Leather": [
        "Split Leather"
      ]
    },
    "RSW1C": {
      "Cut Level": [
        "Cut 1"
      ],
      "Requirements": [
        "Contact Heat"
      ],
      "Leather": [
        "Split Leather"
      ],
      "Industry": [
        "Arc Welding",
        "Construction",
        "Engineering",
        "Fabrication",
        "Metal work",
        "Mig Welding",
        "Welding",
        "Work gloves"
      ],
      "Brand": [
        "Predator"
      ],
      "Liner Material": [
        "100% Cotton"
      ]
    },
    "RSW1CBLUE": {
      "Brand": [
        "Predator"
      ],
      "Cut Level": [
        "Cut 1"
      ],
      "Liner Material": [
        "100% Cotton"
      ],
      "Requirements": [
        "Contact Heat"
      ],
      "Leather": [
        "Split Leather"
      ],
      "Industry": [
        "Arc Welding",
        "Construction",
        "Engineering",
        "Fabrication",
        "Forging",
        "Mig Welding"
      ]
    },
    "RSW1CBLUES": {
      "Brand": [
        "Planetsafe"
      ],
      "Cut Level": [
        "Cut 1"
      ],
      "Liner Material": [
        "100% Cotton"
      ],
      "Requirements": [
        "Contact Heat"
      ],
      "Leather": [
        "Split Leather"
      ],
      "Industry": [
        "Arc Welding",
        "Construction",
        "Engineering",
        "Fabrication",
        "Forging",
        "Mig Welding"
      ]
    },
    "RSW1CKEV": {
      "Brand": [
        "Predator"
      ],
      "Cut Level": [
        "Cut 1"
      ],
      "Liner Material": [
        "100% Cotton"
      ],
      "Requirements": [
        "Contact Heat"
      ],
      "Leather": [
        "Split Leather"
      ],
      "Industry": [
        "Arc Welding",
        "Construction",
        "Engineering",
        "Fabrication",
        "Metal work",
        "Mig Welding"
      ]
    },
    "RSW1CREV": {
      "Brand": [
        "Predator"
      ],
      "Cut Level": [
        "Cut 1"
      ],
      "Liner Material": [
        "100% Cotton"
      ],
      "Requirements": [
        "Contact Heat"
      ],
      "Leather": [
        "Split Leather"
      ],
      "Industry": [
        "Arc Welding",
        "Construction",
        "Engineering",
        "Fabrication",
        "Metal work",
        "Mig Welding"
      ]
    },
    "SL1HRF": {
      "Cut Level": [
        "Cut F"
      ],
      "Requirements": [
        "Contact Heat"
      ],
      "Industry": [
        "Agriculture",
        "Automotive",
        "Engineering",
        "Sheet work",
        "Welding"
      ],
      "Style": [
        "Sleeves"
      ],
      "Gauge": [
        "13"
      ]
    },
    "SL2CLD": {
      "Cut Level": [
        "Cut D"
      ],
      "Industry": [
        "Agriculture",
        "Automotive",
        "Engineering",
        "Sheet work",
        "Welding"
      ],
      "Style": [
        "Sleeves"
      ],
      "Gauge": [
        "18"
      ]
    },
    "SL3VIPD": {
      "Cut Level": [
        "Cut D"
      ],
      "Industry": [
        "Agriculture",
        "Automotive",
        "Engineering",
        "Sheet work",
        "Welding"
      ],
      "Style": [
        "Sleeves"
      ],
      "Gauge": [
        "13"
      ]
    },
    "SN13DTQ": {
      "Coating": [
        "Sandy Nitrile"
      ],
      "Cut Level": [
        "Cut D"
      ],
      "Requirements": [
        "Contact Heat",
        "Cut protection",
        "Touchscreen",
        "Vend Ready"
      ],
      "Liner Material": [
        "Spandex liner",
        "UHMWPE",
        "Polyethylene"
      ],
      "Industry": [
        "Agriculture",
        "Construction",
        "Food Industry",
        "Glass",
        "Glazing",
        "Landscaping",
        "Metal work",
        "Packaging",
        "Scaffolding",
        "Touchscreens",
        "Warehousing"
      ],
      "Gauge": [
        "13"
      ]
    },
    "TS1": {
      "Coating": [
        "Polymax"
      ],
      "Cut Level": [
        "Cut 1"
      ],
      "Requirements": [
        "Foodsafe",
        "Touchscreen"
      ],
      "Liner Material": [
        "Nylon Liner",
        "Spandex liner"
      ],
      "Industry": [
        "Assembly",
        "Automotive",
        "Engineering",
        "Food Industry",
        "Touchscreens"
      ],
      "Gauge": [
        "15"
      ]
    },
    "TS4": {
      "Coating": [
        "Polymax"
      ],
      "Cut Level": [
        "Cut F"
      ],
      "Requirements": [
        "Contact Heat",
        "Cut protection",
        "Foodsafe",
        "Impact",
        "Touchscreen"
      ],
      "Liner Material": [
        "Nylon Liner",
        "Spandex liner",
        "Tekarmor"
      ],
      "Industry": [
        "Automotive",
        "Fabrication",
        "Food Industry",
        "Glass",
        "Glazing",
        "Metal work",
        "Touchscreens"
      ],
      "Gauge": [
        "18"
      ]
    },
    "WPTL7CL": {
      "Requirements": [
        "Contact cold",
        "Thermal"
      ],
      "Liner Material": [
        "Polyester Liner"
      ],
      "Industry": [
        "Cold stores",
        "Scaffolding",
        "Agriculture",
        "Banksmen",
        "Construction",
        "Engineering"
      ],
      "Gauge": [
        "7"
      ],
      "Coating": [
        "Crinkle Latex"
      ],
      "Cut Level": [
        "Cut 1"
      ]
    },
    "WS1": {
      "Coating": [
        "Latex"
      ],
      "Cut Level": [
        "Cut 1"
      ],
      "Requirements": [
        "Contact Heat",
        "Waterproof"
      ],
      "Liner Material": [
        "Nylon Liner",
        "Spandex liner"
      ],
      "Industry": [
        "Banksmen",
        "Construction",
        "Engineering",
        "General Handling",
        "Landscaping",
        "Scaffolding",
        "Work gloves"
      ],
      "Gauge": [
        "15"
      ]
    },
    "WS4": {
      "Coating": [
        "Latex"
      ],
      "Cut Level": [
        "Cut 2",
        "Cut level B"
      ],
      "Requirements": [
        "Contact Heat",
        "Waterproof"
      ],
      "Liner Material": [
        "Acrylic liner",
        "Polyester Liner"
      ],
      "Industry": [
        "Cold stores",
        "Construction",
        "Engineering",
        "Landscaping",
        "Logistics",
        "Scaffolding",
        "Work gloves"
      ],
      "Gauge": [
        "15"
      ]
    },
    "WS5": {
      "Coating": [
        "Sandy Nitrile"
      ],
      "Cut Level": [
        "Cut E"
      ],
      "Requirements": [
        "Contact cold",
        "Contact Heat",
        "Thermal",
        "Waterproof"
      ],
      "Liner Material": [
        "Acrylic liner",
        "Polyester Liner",
        "Steel liner"
      ],
      "Industry": [
        "Cold stores",
        "Construction",
        "Engineering",
        "Metal work",
        "Recycling",
        "Waste Management"
      ],
      "Gauge": [
        "13"
      ]
    },
    "WS6": {
      "Coating": [
        "Latex"
      ],
      "Cut Level": [
        "Cut 1"
      ],
      "Requirements": [
        "Waterproof"
      ],
      "Gauge": [
        "13"
      ],
      "Liner Material": [
        "Polyester Liner"
      ],
      "Industry": [
        "Banksmen",
        "Construction",
        "Engineering",
        "General Handling",
        "Landscaping",
        "Scaffolding"
      ]
    },
    "WS7": {
      "Coating": [
        "Latex"
      ],
      "Cut Level": [
        "Cut E"
      ],
      "Requirements": [
        "Contact cold",
        "Cut protection",
        "Thermal",
        "Waterproof"
      ],
      "Industry": [
        "Cold stores",
        "Glass",
        "Recycling",
        "Waste Management",
        "Construction",
        "Engineering",
        "General Handling"
      ],
      "Gauge": [
        "15"
      ],
      "Liner Material": [
        "Polyester Liner",
        "Steel liner"
      ]
    },
    "WS8": {
      "Coating": [
        "Nitrile"
      ],
      "Cut Level": [
        "Cut 1"
      ],
      "Requirements": [
        "Contact Heat",
        "Waterproof"
      ],
      "Gauge": [
        "15"
      ],
      "Liner Material": [
        "Nylon Liner"
      ],
      "Industry": [
        "Cold stores",
        "Construction",
        "Engineering",
        "General Handling",
        "Landscaping",
        "Scaffolding"
      ]
    },
    "WS9": {
      "Coating": [
        "Nitrile"
      ],
      "Cut Level": [
        "Cut F"
      ],
      "Requirements": [
        "Contact Heat",
        "Cut protection",
        "Waterproof"
      ],
      "Industry": [
        "Banksmen",
        "Engineering",
        "Glass",
        "Recycling",
        "Work gloves"
      ],
      "Gauge": [
        "13"
      ],
      "Liner Material": [
        "Nylon Liner",
        "Spandex liner"
      ]
    }
  },
  "featureCategories": [
    "Coating",
    "Cut Level",
    "Liner Material",
    "Requirements",
    "Style",
    "Leather",
    "Gauge",
    "Test Category"
  ]
};
